### ISSUE TITLE
Windows 10/64bit Crashes my PC

### ISSUE THREAD

**Issue by sides580** [zcoinofficial/zcoin#102]
8.7.8 randomly reboots(crashes) my main PC. Can't sync. My laptop is able to sync with both 8.7.8 and 8.7.7. My main PC could never fully sync. After updating to 8.7.8, my PC now just reboots randomly after opening the wallet. The only thing that might be unique is my PC is always running mining software and keeping my GPU's at 100%. Other then that, i have no problems with any other software on my PC. Haven't looked closely at log files. Any recommendations?

**Comment by leoreinaux** [comment]
Make a test without the mining software, the wallet uses a lot of CPU to do initial sync, your motherboard could overheat doing both things and reboot. Look at debug.log too, it can show you what problem is happening

**Comment by sides580** [comment]
Thanks. You were right, must have been overloading something on my motherboard. Strange. The wallet still had trouble but I deleted all my zcoin files and started without my wallet.dat file. Once it was updated, I replaced the wallet.dat with mine and all went well.
