### ISSUE TITLE
Zcoin OSX wallet does not generate wallet.dat

### ISSUE THREAD

**Issue by rainbowstain** [zcoinofficial/zcoin#107]
**Symptom**
![zcoin-error](https://user-images.githubusercontent.com/3931856/28236950-05d4055a-696f-11e7-84e9-b9bc0071b7ab.jpg)

It came as a bit of surprise when OSX wallet complained about missing `wallet.dat` file from the initial run. (I believe this file should be auto-generated.) I tried to manually generate the file by running `zcoin-qt` binary in the application with appropriate options, but there simply was no way to do so. 

As a last resort, I ran `zcoind` on a linux host, made `wallet.dat`, and copied the file to get the wallet program started. After that, everything went as expected.

**Environment**
- OSX   : 10.11
- Zcoin :  0.8.7.8

**Comment by iho3in** [comment]
i had this error in windows when i want use backup of wallet.dat .then i got this error also sync is not working for backup of wallet.dat ,it just working for new wallets
so how  can i restore my zcoin ?

**Comment by dingjun1114** [comment]
copy wallet.dat from other platform,such as windows.then run app on osx with flag reindex,everything works well.

**Comment by reubenyap** [comment]
Try download 0.13.3.3 and delete peers.dat and banlist.dat then do a reindex.

https://zcoin.io/reindex-zcoin-wallet/
