### ISSUE TITLE
fail to specify rpcconnect ip

### ISSUE THREAD

**Issue by redsnow1992** [zcoinofficial/zcoin#108]
i use: `zcoind  --rpcconnect=192.168.80.19`
but `netstat -anp | grep :8888` still show me `127.0.0.1:8888`
however `rpcport` takes effect  
does anyone can help me?
use  compiled src on master
Thx

**Comment by gemini100** [comment]
hey i m newbie, but what about before calling from external ip make from console:
-rpcallowip=<ip>
Allow JSON-RPC connections from specified source. Valid for <ip> are a single IP (e.g. 1.2.3.4), a network/netmask (e.g. 1.2.3.4/255.255.255.0) or a network/CIDR (e.g. 1.2.3.4/24). This option can be specified multiple times

**Comment by redsnow1992** [comment]
@gemini100 Thx
