### ISSUE TITLE
How to create a private testnet for experimentation?

### ISSUE THREAD

**Issue by dwcc** [zcoinofficial/zcoin#115]

**Comment by DerUntote** [comment]
You need to generate your own genesis block and add nodes of your network. You should have at least 2 nodes for mining blocks.

**Comment by riordant** [comment]
General testnet works quite well if you're looking to experiment.
- build the repo following the instructions in the README
- make a `testnet3/` folder in your zcoin data directory (location depends on your OS; see [here](https://en.bitcoin.it/wiki/Data_directory)
Download a snapshot of the testnet chain [here](https://testnetbootstrap.zcoin.io/)
unpack it into the `testnet3/` folder
go the the src directory (one directory in from where you built this repo), run:
`./zcoind testnet=1 daemon=1`
It will begin syncing. Compare it with the latest block [here](https://testexplorer.zcoin.io/)
see commands for interacting with the chain at
`./zcoin-cli help`
there is no faucet, but to get some testnet coin, you can mine some. run:
./zcoin-cli setgenerate true
