### ISSUE TITLE
OpenSSL compatibility seems to be broken (Fedora 26, openssl-devel 1.1.0f)

### ISSUE THREAD

**Issue by bamfrad** [zcoinofficial/zcoin#116]
I can't compile the wallet, neither the old one nor the Core 0.13 upgrade branch. Here's the entire compiler error dump (starting from 1st error) from the current core_upgrade branch: https://pastebin.com/WvLmRsCd
The old wallet also throws the same errors.

All dependencies are installed and openssl-devel-1.1.0f does provide backwards compatibility to 1.0.2, however this doesn't seem to change the fact that libzerocoin/bitcoin_bignum/bignum.h accesses the OpenSSL bignum module in a way that is unsupported.

I googled around and found these threads about very similar issues with Feathercoin and Bitcoin wallets, respectively:
https://github.com/FeatherCoin/Feathercoin/issues/177
https://github.com/bitcoin/bitcoin/issues/7086

Any chance for a fix?

**Comment by TimurKiyivinski** [comment]
If you've got `openssl-1.0` installed, this should help you:
```sh
./autogen.sh
LDFLAGS=" -L/usr/lib/openssl-1.0 -lssl" CXXFLAGS="-I/usr/include/openssl-1.0" PKG_CONFIG_PATH="/usr/lib/openssl-1.0/pkgconfig" ./configure
make
```
Using the same thing on Arch.

**Comment by initbar** [comment]
I think this [pull request](https://github.com/zcoinofficial/zcoin/pull/111) just landed that deals with this issue.
