### ISSUE TITLE
hi all, two newbi question

### ISSUE THREAD

**Issue by gemini100** [zcoinofficial/zcoin#118]
hi community, i m gemini, thinking Zcoin, egalitary computing policie came at the most hot moment of cryptocurrencies, ecelent choice, i didn't understand nothing, but big picture is pretty ok,

i plan to start solo mining with one of my 3 rigs
6 1060 under win10 with G4400 cpu and 4 Gb ram DDR4

so first) i had search for doc on launch daemon via console of the qt wallet but i m not sure, in facts, i read help command section but no find????
could some one just indicate me some things?

second) is the algo pass to MTP or not yet, on maproad, its august 2017 , it seems to be no, but here too i m deep out.
**most important :+1:** 
thank u reading me, and thanks to the staff of zcoin

**Comment by reubenyap** [comment]
Hi gemini100

See if this guide helps you:
https://zcoin.io/solo-mining-zcoin-guide/

MTP has not yet launched to mainnnet. Still on testnet. We are awaiting for updated academic paper for MTP security and performance improvements before launching.

**Comment by gemini100** [comment]
thank reubenyap for celerity
i , off course, read your ood blog before posting, what i didn't understand is that zcoind is an exe file or a command of wallet . acoind.exe isn't present in my" appdate\zcoin\  " folder
i search in code tree but didn t find it? from here came my interrogations

**Comment by gemini100** [comment]
hi every one i read some documentation
so to start my daemon under win10 i write : on cmd in wallet folder "zcoin-qt.exe" 
i enter this command: zcoin-qt ./zcoind -daemon -conf=zcoin.conf -addnode=127.0.0.1 -connect=127.0.0.1 -seednode=52.178.34.114
it seems to work, but ccminer refuse to connect even if i add upnp in my router,

here is ccminer response: [2017-09-19 12:29:33] NVAPI GPU monitoring enabled.
[2017-09-19 12:29:33] 2 miner threads started, using 'lyra2Z' algorithm.
[2017-09-19 12:29:33] JSON-RPC call failed: Method not found
[2017-09-19 12:29:33] get_work failed, retry after 30 seconds
[2017-09-19 12:29:35] API bind to port 4068 failed - using port 4069
[2017-09-19 12:30:03] JSON-RPC call failed: Method not found
[2017-09-19 12:30:03] get_work failed, retry after 30 seconds

i will later try adding apinbind calling command in deamon call
i m close to do it
