### ISSUE TITLE
Difficulty bomb in algo

### ISSUE THREAD

**Issue by ocminer** [zcoinofficial/zcoin#12]
With the current specs, mining will cease as the Lyra2 algo with block header as rows will grow memory usage beyond realistic limits very soon, diff is ramping up too steep. 

Fix this by setting a hard value or something similar.

**Comment by slugmandrew** [comment]
Hey, @ocminer. Can you or anyone else explain very quickly (or point me to some resources) how the block size growing will make mining unprofitable? I thought I understood that the algo re-targets the difficulty after each block to compensate for this?

**Comment by przeor** [comment]
off-top @slugmandrew can you take a lot at https://github.com/zcoinofficial/zcoin/issues/23 ? I see you've just replied, maybe you have a quick tip with the #23 ?

**Comment by slugmandrew** [comment]
@przeor Sorry, I've looked at it but my technical knowledge of this stuff is very basic. Can't help you bud. Maybe @ocminer can help?
