### ISSUE TITLE
No block source avaliable in OS X wallet

### ISSUE THREAD

**Issue by Saruwatari34** [zcoinofficial/zcoin#122]
<img width="849" alt="screen shot 2560-09-22 at 3 02 58 pm" src="https://user-images.githubusercontent.com/10971147/30734987-9a644630-9fa7-11e7-8533-2e7365c8f7c9.png">

i'm trying use OS X wallet but when sync to 42513 block it show follow pic. and have 8 connection active.

**Comment by DonPedroD** [comment]
Same issue here when starting my ZCoin Wallet on Ubuntu 16.04.
Sync was here to 53841 and currently also 8 active connections.

![zcoin core - wallet _126](https://user-images.githubusercontent.com/21311352/30979720-cd38be48-a47e-11e7-993e-102698cbf75d.png)

**Comment by yomon598** [comment]
Had the issue as well.Not sure exactly what the actual reason for that is, but you can quickly fix it by running the wallet with "-reindex" option and will reindex the blocks on your drive, rather quickly.
After doing so, I've been running with the "-use-thinblocks=0" option and haven't had any problems lately.Not sure if it's just coincidence or not.

**Comment by massno1** [comment]
Having the same issue with OS X wallet, any solutions guys?

**Comment by DonPedroD** [comment]
The solution here was to upgrade to the latest version from the github

**Comment by massno1** [comment]
Thank you for your reply, I have the latest upgrade Zcoin Core version v0.13.2.9 (64-bit).

**Comment by brishtiteveja** [comment]
So, from my investigation about this issue,
The bitcoingui.cpp is checking the block source, when the block source is BLOCK_SOURCE_NONE, the status bar shows "No block source available..."
https://github.com/zcoinofficial/zcoin/blob/a6b3729066175d1ec98e76882eb20bc1b034b677/src/qt/bitcoingui.cpp#L766
Now, when the block source will be BLOCK_SOURCE_NONE, from the clientmodel.cpp, when there is no connection found..
https://github.com/zcoinofficial/zcoin/blob/8cf8f0ebe388b70a3289ae3ddf5abbf375433cd5/src/qt/clientmodel.cpp#L136
It seems the client is having some connection issue when trying to connect in the setClientModel function
https://github.com/zcoinofficial/zcoin/blob/a6b3729066175d1ec98e76882eb20bc1b034b677/src/qt/bitcoingui.cpp#L478

It may be that your client was genuinely not finding any peer node for downloading blocks, or some other bugs. Thank you.

**Comment by reubenyap** [comment]
Try download 0.13.3.3 and delete peers.dat and banlist.dat then do a reindex.

https://zcoin.io/reindex-zcoin-wallet/
