### ISSUE TITLE
Error building as a static library

### ISSUE THREAD

**Issue by Adeliscod** [zcoinofficial/zcoin#129]
I need to compile the app in a static form where the binary that outputs doesn't require the installation of more libraries. For example:  

"zcoind: error while loading shared libraries: libboost_program_options.so.1.58.0: cannot open shared object file: No such file or directory." This happens when I move the binary and try to compile it in another server. 

Thanks

**Comment by devwarrior777** [comment]
BTW I do not attempt to sign any of the packages with a GPG key although there is that possibility in the **gitian-builder** tools

Have fun ;-)

**Comment by devwarrior777** [comment]
@sn-ntu thanks for your help
