### ISSUE TITLE
error: incorrect rpcuser or rpcpassword (authorization failed)

### ISSUE THREAD

**Issue by warcries** [zcoinofficial/zcoin#137]
I'm on the Step 3.2 Generate znodeprivkey. When I generate the znodeprivkey this is the err "error: incorrect rpcuser or rpcpassword (authorization failed)"

**Comment by pawin** [comment]
I having this issue too, anyone knows how to fix?

**Comment by coolcow** [comment]
same here

**Comment by coolcow** [comment]
i got it working. you have to create a `.zcoin/zcoin.conf` with following content:
```
rpcpassword=some_random_password
```

---

If you are playing with the test-network, you have to add `-testnet` to **ALL** `zcoin-cli` commands (this is'nt mentioned int the [ZNODE.md](https://github.com/zcoinofficial/zcoin/blob/znode/ZNODE.md)):
```
zcoin-cli -testnet znode genkey
zcoin-cli -testnet getaccountaddress 0
```
