### ISSUE TITLE
Znode setup guide improvement

### ISSUE THREAD

**Issue by o0oBluePhoenixo0o** [zcoinofficial/zcoin#139]
Hi, 

These are my findings after a day trying to setting up my Znode. Much appreciate for the FAQ but I believe it is still a bit ... vague. Here are the points:

Assuming you have a running VPS:
1. Clone git branch "znode" into a different folder ( if you already have cloned the core_upgrade branch)
2. cd into the folder you just cloned (main working environment)
3. Install all the packages from the requirement list (https://github.com/zcoinofficial/zcoin/blob/znode/README.md)
4. Run "autogen.sh" and "configure" there. Then "make" and "make check"
5. Set up the conf file (step 4 in znode setup https://github.com/zcoinofficial/zcoin/blob/znode/ZNODE.md) BEFORE RUNNING DAEMON TEST NET(step 3). You should delete out the znode=1 and privatekey line
6. Proceed to generate private key and continue through the steps as normal

**Comment by rainbowstain** [comment]
I've uploaded a Docker recipe that compiles binaries. 
Just copy and paste two lines.

<https://github.com/rainbowstain/zcoin-docker>

**Comment by riordant** [comment]
@reubenyap please review

**Comment by devwarrior777** [comment]
Hi, do you actually need to compile and build the code?

Runnable binaries are here:

https://github.com/zcoinofficial/zcoin/releases/tag/v0.13.5.8 and click `zcoin-qt-0.13.5.8-linux64.tar.gz`
You can then use *wget* 
May we close this issue?
