### ISSUE TITLE
EXCEPTION: St12out_of_range

### ISSUE THREAD

**Issue by eTiMaGo** [zcoinofficial/zcoin#143]
I have successfully compiled and run a testnet node after the 22/11 updates, but I am repeatedly getting this error in the terminal:

`************************`
`EXCEPTION: St12out_of_range`
`CInv::GetCommand(): type=1073741826 unknown type`
`zcoin in ProcessMessages() 2`

**Comment by reubenyap** [comment]
Yup this is a known issue and will be solved in next code push. Thanks for informing!
