### ISSUE TITLE
g++: internal compiler error: Segmentation fault (program cc1plus)

### ISSUE THREAD

**Issue by oti-dev** [zcoinofficial/zcoin#147]
Hello,

I've encountered a rather disturbing issue, I'm unsure of the reason for this to happen. While trying to compile zcoin code (using Ubuntu 16.04 as subsystem of Win10) I get following message:

> g++: internal compiler error: Segmentation fault (program cc1plus)
> Please submit a full bug report,
> with preprocessed source if appropriate.
> See <file:///usr/share/doc/gcc-6/README.Bugs> for instructions.
> Makefile:5340: recipe for target 'primitives/libbitcoin_util_a-block.o' failed

I googled a bit, and a solution I found was to try and build with different version of gcc.. I've tried following versions:

> Selection    Path              Priority   Status
> ------------------------------------------------------------
>   0            /usr/bin/gcc-4.4   80        auto mode
>   1            /usr/bin/gcc-4.4   80        manual mode
>   2            /usr/bin/gcc-4.8   70        manual mode
>   3            /usr/bin/gcc-4.9   80        manual mode
> * 4            /usr/bin/gcc-5     50        manual mode
>   5            /usr/bin/gcc-6     60        manual mode

None of which worked. My question is - what versions of GCC-G++ do you find to be working perfectly with zcoin, so that I can move on to another approach on solving my problem?

P.S. I'm quite aware that the issue I've encountered has not much to do with actual zcoin project, but rather my system configuration, but if you have any idea what might cause the problem, I'd be thankful for instructions.

**Comment by oti-dev** [comment]
Still no clue what was wrong, but I worked that around by building for windows with mingw. Windows is my target anyway, so that suits me, but the issue is curious nevertheless.

**Comment by psolstice** [comment]
It's already fixed in this commit
https://github.com/zcoinofficial/zcoin/commit/c9e3ad46fd9eee558a2045a18e058dcb8f0f650d
it's not in master though, you'll have to apply the patch manually
