### ISSUE TITLE
Can't find Zcoin data directory on Mac

### ISSUE THREAD

**Issue by Squeekycleen** [zcoinofficial/zcoin#152]
Hi-

I'm trying to find my Zcoin data directory on my Mac, but it does not appear to be at $HOME/Library/Application Support/zcoin/ where the znode document says it should be. 

Can anyone help?

**Comment by ChairmanMeow** [comment]
did you start the wallet app? once you start it, it will create it for u

**Comment by reubenyap** [comment]
~/Library/Application Support/zcoin

unless you specified it in a different place
