### ISSUE TITLE
Wallet is not syncing. "No block source available"

### ISSUE THREAD

**Issue by darthcrypto87** [zcoinofficial/zcoin#158]
The last 3 days I had the issue that my wallet says "no block source available".
After it first happened I downloaded the folders blocks and chainstate from my VPS and it worked after that.
The next day the issue occured again. I then reindexed.
The next day, today, I started the wallet in the morning but then the issue occured again, this time with my wallet being open all day.

In the attached debug.log if you search for "2017-12-21 14:23:20 Shutdown: done" you find the shutdown I did after I noticed that the issue occured.

[debug.log](https://github.com/zcoinofficial/zcoin/files/1580079/debug.log)

**Comment by darthcrypto87** [comment]
The issue occured with wallet version 0.13.4.2. I wasn't aware of the new version.
I'm running 0.13.4.3 since yesterday and the issue has not occured so far.

**Comment by darthcrypto87** [comment]
The problem occured again 3 days ago with version 0.13.4.3

**Comment by ByCnck** [comment]
same problems

**Comment by bryanj4** [comment]
I'm getting the same issue on my Windows computer and here are some of the errors I am getting: 
```2018-01-26 15:57:04 init message: Loading znode cache...
2018-01-26 15:57:04 Reading info from mncache.dat...
2018-01-26 15:57:04 ERROR: Read: Failed to open file C:\Users\USERNAME\AppData\Roaming\zcoin\mncache.dat
2018-01-26 15:57:04 Missing file mncache.dat, will try to recreate
2018-01-26 15:57:04 init message: Znode cache is empty, skipping payments and governance cache...
2018-01-26 15:57:04 init message: Loading fulfilled requests cache...```

**Comment by Surfmonkey65** [comment]
updated to the latest wallet today and receiving the same issue. From the error log - "2018-03-08 20:43:37 CZnodePing::CheckAndUpdate -- Znode ping is invalid, block hash is too old:".  Has anyone identified a work around?

**Comment by soerenmartius** [comment]
+1 here, anybody got an answer on this ever?

**Comment by riordant** [comment]
Hi, can you please try the latest version 0.13.5.8. If this continues to happen, in the GUI itself, going to the 'Znode' tab often triggers the GUI to start syncing. If not, a reindex is required - so start the GUI with the `reindex` flag.

**Comment by reubenyap** [comment]
Closing this issue. if you are still having problems, please do reopen it.
