### ISSUE TITLE
syncing got stuck and very slow confirms

### ISSUE THREAD

**Issue by Himan2001** [zcoinofficial/zcoin#159]
Today i noted on bittrex an extremly slow Tx confirm. They need for 6/6 confirms more then 2 1/2 hours.
it was stuck on 3/6 most of the time.

A few days before i synced the blockchain at home on my vserver and i needed massive manual restarts to overcomes the timeouts and hungs. Finaly this restarts i must made for the last 20% nearly every minute.

I switched off addnodes, dnsseed and searched for stable datacenter nodes with long uptimes and checked their used wallet versions. Finaly i added a maximum of 5 static nodes with connect=. Then syncing was errorfree and fast. On my windows wallet, that is still using p2p/addnode and a few basic addnodes, resync after 3 days is no longer possible without made here the same manual setup as i made for the linux-wallet.

At the moment by using the dnsseed the wallet receives an enormous amount of orphans and this produces the continous hickups and hungs. Logfile statet often that wallet is in a loop then.

Please investigate this issues more, disable older clients by rising minimum version numbers and search for the real reasons, why the confirmations have reached the slowness of BTC ;-)

**Comment by riordant** [comment]
Hi Himan2001,
are you still experiencing the same issues as of the later clients?

**Comment by reubenyap** [comment]
Please try 13.5.8 which should resolve this a lot better. Report back if it still is an issue.
