### ISSUE TITLE
upgraded from 0.13.3.2 (win64) to 0.13.4.3 (win64) ，stuck in the 60032 block

### ISSUE THREAD

**Issue by ttt2008** [zcoinofficial/zcoin#160]
I upgraded from 0.13.3.2 (win64) to 0.13.4.3 (win64) and with the "delete all files and directories other than wallet.dat, run a new executable" method, I found the card stuck on the 60032 , Use the-reindex logo to start again, but still stuck in the 60032 block, how should I deal with?

**Comment by reubenyap** [comment]
Could you try deleting peers and banned before doing a reindex?

**Comment by reubenyap** [comment]
Upgrade to the latest version 13.5.6 and reindex this should solve it.
