### ISSUE TITLE
Syncing is prevented if the first peer has fewer blocks

### ISSUE THREAD

**Issue by destenson** [zcoinofficial/zcoin#161]
While downloading blocks, the client should check the block length of each peer & disconnect from the ones with fewer blocks that the client. 

I just had this issue when I after opening the client (even twice), it got stuck on block 66699. When I opened the Peers list, the first peer in the list had a shorter blockchain than I did. It was stuck on that block for several minutes, but within seconds after disconnecting from that peer, the download resumed.

There are probably a number of ways this bug could be fixed, but I think it probably should just disconnect from any peer with a shorter chain while it's synchronizing.

**Comment by reubenyap** [comment]
@destenson Just to let you know @psolstice is looking into this now. Apologies for the long delay.

**Comment by riordant** [comment]
@psolstice Is this still relevant? Did we ever implement this is something like it?

**Comment by psolstice** [comment]
We need to check if sync-fix made things better. After sync-fix our behavior regarding syncing is the same as that of bitcoin and we shouldn't touch that

**Comment by psolstice** [comment]
Closing it for now as there is no feedback
