### ISSUE TITLE
serial number 0

### ISSUE THREAD

**Issue by real-or-random** [zcoinofficial/zcoin#164]
5bb562f18eef8400f33b66d1627f6722930e746e is a hardfork, because it rejects serialNumber 0, which was not rejected before. Furthermore, it's not necessary, see https://github.com/zcoinofficial/zcoin/blob/master/src/libzerocoin/SerialNumberSignatureOfKnowledge.cpp#L116.

**Comment by psolstice** [comment]
Technically you're right about hardfork. But we never encountered zero serial numbers in the past so it doesn't matter at the moment

The patch is still needed to reject coin with serial number of zero, new conditions are stronger than ones you're referencing

**Comment by real-or-random** [comment]
What if you encounter a zero serial number tomorrow?

**Comment by real-or-random** [comment]
What happens then?
