### ISSUE TITLE
listunspent stops working properly

### ISSUE THREAD

**Issue by rami-dabain** [zcoinofficial/zcoin#165]
- Compiled new version 2nd Jan 2018 (linux)
- ./zcoind -daemon=1 -reindex=1 -txindex=1 -addressindex=1
after looooong time (reindex and downloading the blockchain)

listunspent 1 99999 '["ADDRESS THAT IS NOT IN YOUR WALLET"]'
worked ! as supposed to

next day, it stopped working for no reason, nothing has been changed after the compiling (and the zcoin.conf before the reindex)

**Comment by nopslide** [comment]
we don't have addressindex option.

**Comment by riordant** [comment]
Hi, firstly we do have `addressindex`. Have you first imported the non-wallet address? You can do this with the `importwallet` command.

**Comment by riordant** [comment]
@rami-dabain Could you give more info on this? 
- Does the issue occur for any address outside of the wallet?
- What exactly is meant by "worked ! as supposed to"? It doesn't show all outputs?

**Comment by riordant** [comment]
Closing due to inability to replicate issue
