### ISSUE TITLE
core.26725 file

### ISSUE THREAD

**Issue by Newar417** [zcoinofficial/zcoin#166]
In my `/bin` folder there is a core.26725 file. It is not readily human readable. What is the purpose of this file?

v0.13.4

**Comment by nopslide** [comment]
can you give more information ?

**Comment by Newar417** [comment]
Not sure what to add. Maybe a pic helps?

![selection_003](https://user-images.githubusercontent.com/7670917/34623635-8da0f574-f295-11e7-97f7-457f199c5196.jpg)

![selection_004](https://user-images.githubusercontent.com/7670917/34623649-95cf2a90-f295-11e7-8ff4-6473feeaa160.jpg)

**Comment by Newar417** [comment]
It seems to be a dump file of sorts. In the last two weeks, twice my MN has gone from "Enabled" to "New Start Required" and the time-stamp of those files match roughly with the change in status.

I have now checked on the VPS and the MN stopped running.

**Comment by Newar417** [comment]
Trying to restart, getting this error:

> Zcoin server starting
zcoind: main.cpp:2913: bool ConnectBlock(const CBlock&, CValidationState&, CBlockIndex*, CCoinsViewCache&, const CChainParams&, bool): Assertion `hashPrevBlock == view.GetBestBlock()' failed.

**Comment by reubenyap** [comment]
Please try with the latest version 13.5.8 but if you are still experiencing issues, or happens again, please attach the core dump file and the version you were using.
