### ISSUE TITLE
Trezor integration - Bitcore Insight Server

### ISSUE THREAD

**Issue by Technoprenerd** [zcoinofficial/zcoin#167]
The Trezor integration pull request has been added: https://github.com/trezor/trezor-common/pull/62 

For this to work, the Bitcore Insight Server needs to be compatible.

Currently, it has these errors: 
- https://github.com/bitpay/bitcoin/issues/17
- https://github.com/bitpay/insight/issues/719

These bugs/features should be added inside the zcoin source.

**Comment by nopslide** [comment]
@Technoprenerd thank you.

**Comment by Technoprenerd** [comment]
Bitcore Insight server:
http://104.238.167.123/insight/

Only needs SSL/https support.
