### ISSUE TITLE
Fee estimation always returns -1

### ISSUE THREAD

**Issue by devwarrior777** [zcoinofficial/zcoin#170]
**Fee estimation using the `estimatefee` or `estimatesmartfee` RPC calls is always returning -1**

The RPC call is reaching the src/rpc/mining.cpp code and then the src/txmempool code but always seems to return -1 from the BlockEstimator.

It would be helpful for the atomicswaps tool to be able to get a good estimate of the latest fees being paid so that it can fill in a reliable fee as a parameter when it calls the `fundrawtransaction` RPC call. Currently we are calling `getinfo` and using the  "relayfee": 0.00100000 parameter.

Thanks

**Comment by sn-ntu** [comment]
Sure, it is helpful to have it works. Thanks!

**Comment by riordant** [comment]
On mainnet, a fee estimate is returned up to around 25 blocks currently. Testnet does return -1 regardless of input, although I think this is likely due to the fact that there is no fee.

**Comment by devwarrior777** [comment]
That is great although I believe from experiment that it varies with the volume of transactions over the preceding blocks.

**Comment by devwarrior777** [comment]
I am closing this issue as we have a workaround for Atomic Swaps code. Thank you for all your input.

**Comment by devwarrior777** [comment]
Still not fixed and estimate fee also does not work. 

- This means that fee estimation on `electrum_xzc` will not work.
- In general fee system for zcoin is broken allowing most transactions with the minimum relay fee (value can be seen from getinfo)

**Comment by riordant** [comment]
Fixed as of https://github.com/zcoinofficial/zcoin/releases/tag/v0.13.7.7
As per @a-bezrukov comment:
- Please delete `fee_estimates.dat` in your data directory, and wait 30-60 mins for fee stats to be gathered.

**Comment by devwarrior777** [comment]
Thanks for the update ...
