### ISSUE TITLE
Take uptime to consideration for znode reward

### ISSUE THREAD

**Issue by kp0z** [zcoinofficial/zcoin#176]
Hi guys,

I got a better understanding thanks to @oti-dev on #174 

So uptime so far is just used as an **entry requirement** for shortlist

Could we consider uptime as another factor for the sorting algorithm inside the shortlist? E.g: the longer uptime a znode is, the higher rank it becomes?

Thanks.

**Comment by catchingknives** [comment]
So you want to shortlist the shortlist? E.g. if uptime > uptime of 50% of shortlist, they should end up in the shortlisted shortlist and be more likely to be selected? 

Why do you want earlier nodes to benefit? I feel they are already benefiting/have already benefited from the fact that they have been set up at a time when fewer nodes existed. For example the first few payouts in late December/early January happened on very short time frames (like 5 days) which will probably never be possible again. People there got paid twice more than once if you know what I mean.

If you're referring to the fact that it's actually possible to move along nicely with the queue without being online consistently, that's a valid concern. However I feel it's very theoretical in nature. Who would benefit from taking a few days off after each payout? Why would you put in the effort to bring your node up and down on a schedule like that if there is no benefit? Or can I just not think of one?

**Comment by kp0z** [comment]
so if a longevity node get pay it will be back to the end of qualified queue, i think our qualified queue (sort with last paid block) eliminates **double pay** quite well
e.g. assume 1500 qualified nodes are static, we will have 150 nodes in shortlist, given node X get pay this round, i believe X will wait for 1350 blocks to get back in shortlist

problem with current _lotto_ algo in shortlist is that it doesn't guarantee (? pls correct me if im wrong) that a node will get pay :neckbeard: 
specifically is this algo here https://github.com/zcoinofficial/zcoin/blob/master/src/znode.cpp#L144

uptime is just my suggestion as a proof of service, can definitely use something else as long as it could determine a payment timeframe for nodes fairly 💵

**Comment by MrMonotone** [comment]
This would make it more punishing if your node went down. It would make it harder for people who run their own nodes to be competitive and probably push people who dont need providers to providers. Also, it would further incentivize top nodes to be ddos'd since you are creating an even smaller pool to pick from. 

I am against this. The algorithm is working fine now. Everyone has got paid out eventually. People who dont get paid out because of their own user errors the majority of time. This will get even worse if we add uptime as a parameter.

**Comment by kp0z** [comment]
agree on ddos attack, it could the reason of doing random picking for winner in shortlist, but i wonder how sure are we when say "eventually" there? Might put it this way: how long would it take (relatively) for a node in shortlist to get pay?

uptime is just my suggestion as a proof of service, can definitely use something else as long as it could determine a payment timeframe for nodes fairly

**Comment by MrMonotone** [comment]
We already have an estimate. Its The node amount / 144 block on avg. Which is around 18 days now. The majority of time people dont get paid at this time is because they made their own mistakes by either restarting the node or breaking it some way.

**Comment by kp0z** [comment]
i was relying on that calculation actually 😆 just to realize it's not that correct, when i say relatively before i mean something like **1500 ± n** (blocks)

for me, estimation of qualified nodes / 144 will fall to gambler's fallacy (because chance of particular node in shortlist to win a block reward doesn't _change_ over time)
