### ISSUE TITLE
Berkeley db 4.8 (libdb4.8) not available

### ISSUE THREAD

**Issue by markmoellering** [zcoinofficial/zcoin#179]
When I follow the instructions, I get the following

**_apt-get install libdb4.8-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Package libdb4.8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source_**

**_E: Package 'libdb4.8-dev' has no installation candidate_**

This is after running **_add-apt-repository ppa:bitcoin/bitcoin_**

Anyone else have this problem? 
This is on a pretty new install of Debian Stretch on a Windows-10 Pro Hyper-V virtual machine.

**Comment by riordant** [comment]
Hi Mark, please refer to this - https://askubuntu.com/questions/393289/how-to-install-libdb4-8-dev-or-equivalent-on-13-10 - ie. run `apt-get update` in-between the install of Berkeley db and the PPA

**Comment by reubenyap** [comment]
Please open this again if you are still having issues.
