### ISSUE TITLE
[w64] Slow RPC, zcoin-cli unable to connect

### ISSUE THREAD

**Issue by oti-dev** [zcoinofficial/zcoin#181]
Hello,

I've noticed that on windows, the RPC commands sent to zcoin node take significant time to be processed - each command takes about 3-4 seconds(even a simple getinfo), and it's not a connection issue - there are other things working on that server and they reply instantly. 

To work around this issue, I've tried to use local zcoin-cli client instead of sending them directly through HTTP.. And it seems that cli is not working at all. Every request results in "error: couldn't connect to server".

zcoin.conf file:

>server=1
>rpcuser=oti
>rpcpassword=oti

Note that the issue only occurs on windows builds - on linux everything works as expected. I built latest master ( last commit: https://github.com/zcoinofficial/zcoin/commit/20c721cf84afb2dcbe1b9096a730e97ff97528bc ) using windows10+WSL.

Checked on: Win10-x64, Win Server 2008 R2 Standard SP1 x64

**Comment by psolstice** [comment]
Please try this patch from different branch (soon it will make its way to the master)
https://github.com/zcoinofficial/zcoin/commit/d4401a0b17de44baffd5788eb71247d7365019cc

It updates libevent so you'll need to build your dependencies after applying this

**Comment by oti-dev** [comment]
Awesome, that fixed it. :)
Thank you for the quick and accurate response.
