### ISSUE TITLE
Zcoin 0.13.5.5 Linux binaries libboost_system.so.1.58.0

### ISSUE THREAD

**Issue by romanornr** [zcoinofficial/zcoin#186]
Can't run the linux binaries.

on my arch machine
```
 ✘ romano@arch  ~/Downloads/zcoin-qt-0.13.5.5-linux64/zcoin-0.13.5/bin  ./zcoin-qt 
./zcoin-qt: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```
on centos
```
@znode01 ~]# zcoind 
zcoind: error while loading shared libraries: libboost_system.so.1.58.0: cannot open shared object file: No such file or directory
```
I think binaries should work without a problem.
Otherwise I will start to compile if that works. Still worth to mention this issue.

**Comment by canya-io** [comment]
+1 for this error.

> $ dpkg -s libboost-dev | grep 'Version'
> Version: 1.62.0.1

Ubuntu 17.10

**Comment by DesignerFrames** [comment]
https://github.com/zcoinofficial/zcoin/blob/master/doc/build-unix.md

These dependencies fixed it for me

**Comment by romanornr** [comment]
The binaries should not require to install dependencies.

It seems like Gitian was not used?

**Comment by schinzelh** [comment]
The inclusion of Tor broke Gitian builds. This will need to be fixed as you can't deterministically build Zcoin anymore.

**Comment by ChrLipp** [comment]
zcoin-qt-0.13.4.3-linux64.tar.gz has 22.2 MB,
zcoin-qt-0.13.5.5-linux64.tar.gz has 16.4 MB.

I installed the boost libraries on my system, but then another missing dependency showed up (can't remember which, because then I stopped the upgrade). The release should be statically linked with the dependencies, it seems that this step was forgotten for this release.

It would make sense to test the final release on a system which was set up as described in the https://zcoin.io/zcoin-znode-setup-guide/ . Also I would recommend to update the setup guide to use the current version (it happened for the 0.13.4.3 update).

**Comment by schinzelh** [comment]
I have fixed the build system in https://github.com/zcoinofficial/zcoin/pull/187

If someone wants to test the Linux binaries: https://transfer.sh/GnRM8/zcoin-0.13.5-x86_64-linux-gnu.tar.gz

**Comment by romanornr** [comment]
Thanks @schinzelh 
The binary works for me.

**Comment by ChrLipp** [comment]
Works for me.

**Comment by pplonski** [comment]
I think it can be related, when running zcoin-qt on ubuntu 14.04 I got:
```
./zcoin-qt: error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory
```

**Comment by schinzelh** [comment]
In case someone want to test the Mac OS X builds for https://github.com/zcoinofficial/zcoin/commit/2bec38cc6888dd56d161980517e4ec0912d3534e

![image](https://user-images.githubusercontent.com/636669/36965717-c11f5736-205a-11e8-9571-1a028673a32d.png)


https://transfer.sh/109Jqv/zcoin-0.13.5-osx-unsigned.dmg

**Comment by schinzelh** [comment]
https://github.com/zcoinofficial/zcoin/tree/v0.13.5.6 is out, with gitian built binaries apparently :)

**Comment by reubenyap** [comment]
Yes thanks @schinzelh there were other issues that we had to address as well to have the gitian working properly. I'm closing this :D

**Comment by ChrLipp** [comment]
@reubenyap Wouldn't it make sense to update https://zcoin.io/zcoin-znode-setup-guide/ as well to point to the 0.13.5.6 release instead of 0.13.4.3?
