### ISSUE TITLE
undefined reference to `SSL_CIPHER_find'

### ISSUE THREAD

**Issue by oti-dev** [zcoinofficial/zcoin#188]
Hello,

I'm struggling with building the newest zcoin 0.13.5.6. I'm getting an error:

 CXXLD    zcoind
tor/src/common/libor-crypto.a(tortls.o): In function `tor_tls_classify_client_ciphers':
tortls.c:(.text+0x4f7): undefined reference to `SSL_CIPHER_find'

Is there any fix for this?

**Comment by oti-dev** [comment]
Idk, after updating the repo once more and rebuilding again, now I get error:

src/or/libtor.a(main.o): In function `tor_main':
main.c:(.text+0x7f61): undefined reference to `evutil_secure_rng_set_urandom_device_file'
src/common/libor-event.a(compat_libevent.o): In function `tor_gettimeofday_cache_clear':
compat_libevent.c:(.text+0x840): undefined reference to `event_base_update_cache_time'
collect2: error: ld returned 1 exit status

What's that about?

**Comment by riordant** [comment]
Hi, what OS are you using? Can you try upgrading to the latest 0.13.5.8 and try again?

**Comment by reubenyap** [comment]
Hi oti-dev, are you still having this issue? Please reopen if so.

**Comment by riordant** [comment]
Reopening this as I have encountered the issue myself.
I think there is some issue with the version of Tor we have.
The issue only seems to occur when building the dependancies for Linux in the `depends` folder

steps to reproduce:
```
cd depends
make HOST=x86_64-linux-gnu -j`nproc` (or x86_64-unknown-linux-gnu)
cd ..
./autogen.sh
./configure --prefix=`pwd`/depends/x86_64-linux-gnu
sudo make -j`nproc`
```

Output:
```
src/or/libtor-testing.a(src_or_libtor_testing_a-main.o): In function `tor_run_main':
main.c:(.text+0x934d): undefined reference to `evutil_secure_rng_set_urandom_device_file'
collect2: error: ld returned 1 exit status
Makefile:4785: recipe for target 'src/test/fuzz/fuzz-consensus' failed
make[3]: *** [src/test/fuzz/fuzz-consensus] Error 1
make[3]: *** Waiting for unfinished jobs....
src/or/libtor-testing.a(src_or_libtor_testing_a-main.o): In function `tor_run_main':
main.c:(.text+0x934d): undefined reference to `evutil_secure_rng_set_urandom_device_file'
collect2: error: ld returned 1 exit status
Makefile:4805: recipe for target 'src/test/fuzz/fuzz-diff' failed
make[3]: *** [src/test/fuzz/fuzz-diff] Error 1
src/or/libtor-testing.a(src_or_libtor_testing_a-main.o): In function `tor_run_main':
main.c:(.text+0x934d): undefined reference to `evutil_secure_rng_set_urandom_device_file'
collect2: error: ld returned 1 exit status
Makefile:4795: recipe for target 'src/test/fuzz/fuzz-descriptor' failed
make[3]: *** [src/test/fuzz/fuzz-descriptor] Error 1
make[3]: Leaving directory '/drive/zcoin-personal/zcoin/src/tor'
Makefile:3472: recipe for target 'all' failed
make[2]: *** [all] Error 2
make[2]: Leaving directory '/drive/zcoin-personal/zcoin/src/tor'
Makefile:11219: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/drive/zcoin-personal/zcoin/src'
Makefile:690: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1
```

**Comment by riordant** [comment]
@psolstice please review

**Comment by psolstice** [comment]
Looks like outdated `libevent`. Try to upgrade to the version `bitcoin` uses

**Comment by riordant** [comment]
As described in `packages`? It is already at the Bitcoin version (you have updated it already).

**Comment by psolstice** [comment]
Can you find `libevent.a`/`libevent.so.*` and do `nm libevent.a | grepevutil_secure_rng_set_urandom_device_file` ? I suspect it picks up the wrong libevent library
