### ISSUE TITLE
Incorrect links in About dialog

### ISSUE THREAD

**Issue by muztek85** [zcoinofficial/zcoin#189]
Links should be updated to point to zcoin website / github
**************
Zcoin Core version v0.13.5.6-2bec38c (64-bit)

Copyright (C) 2009-2018 The Zcoin Core developers
Copyright (C) 2009-2018 The Bitcoin Core developers

Please contribute if you find Zcoin Core useful. Visit https://bitcoincore.org for further information about the software.
The source code is available from https://github.com/bitcoin/bitcoin.

**Comment by riordant** [comment]
Hi muztek85, you are welcome to make a pull request for these changes which we will review ASAP.

**Comment by muztek85** [comment]
Done 
https://github.com/zcoinofficial/zcoin/pull/200
