### ISSUE TITLE
no blocksource available with version v0.13.5.6

### ISSUE THREAD

**Issue by eisgold** [zcoinofficial/zcoin#190]
has connections, but no blocksource, numbers of masternodes has halfed

**Comment by reubenyap** [comment]
Could you test with the latest 13.5.8 and let me know if this issue is still present?

**Comment by eisgold** [comment]
RY> Could you test with the latest 13.5.8 and let me know if this issue is still present?
RY> —
RY> You are receiving this because you authored the thread.
RY> Reply to this email directly, view it on GitHub, or mute the thread.
RY>   
RY>     
RY> {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/zcoinofficial/zcoin","title":"zcoinofficial/zcoin","subtitle":"GitHub
RY> repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open
RY> in
RY> GitHub","url":"https://github.com/zcoinofficial/zcoin"}},"updates":{"snippets":[{"icon":"PERSON","message":"@reubenyap
RY> in #190: Could you test with the latest 13.5.8 and let me know if this issue is still
RY> present?"}],"action":{"name":"View
RY> Issue","url":"https://github.com/zcoinofficial/zcoin/issues/190#issuecomment-383068248"}}} 


Hey Reuben,

this issue is 2 month old, it is solved long time ago. Wallet working fine.

By the way, NEM has partnered with WeChat messenger, Shield XSH has partnered with Line (japanese whatsapp messenger).
Maybe zcoin can partner with telegram or even better whatsapp ... ?



Grüße, 

    chris


Eisgold GmbH www.eisgold.de
vertreten durch Christian Hennek 
Kapellenstrasse 16
30625 Hannover (Stadtteil Kleefeld)


mail:    chris@eisgold.de [chris eisgold de] 
telefon: 0511-7860502 (Home)
