### ISSUE TITLE
actual master no longer compilable under ubuntu 16.04 (secp256k error and others)

### ISSUE THREAD

**Issue by Himan2001** [zcoinofficial/zcoin#191]
The actual master is no longer compilable under ubuntu 16.04.
I figured out, that this has todo with the changed configure.ac syntax ?

basicly the secp256k and the univalue subfolders are no longer correctly pre configured
with the initial autogen & configure. Further more the tor-addendum has the same issues
with the initial configure. 

My next question is: why are so many binary snippets from last compile included in the
source code? The code needs a little more cleanup before commited.

**Comment by psolstice** [comment]
Most likely you forgot to run ./autogen.sh before configure

**Comment by Himan2001** [comment]
no. the usual way is exactly this. as i stated, from the subfolders the secp256 and tor folder becames no run and left unconfigured.

**Comment by SharkWipf** [comment]
Did you intend to close this issue? As I can confirm this problem on both Gentoo unstable and Debian Sid.

**Comment by dg98** [comment]
I have the same issue on Debian Sid. v0.13.4.3 still builds fine, v0.13.5.5 and up do not. The error I get during make seems to be related to the tor stuff that was added.
