### ISSUE TITLE
Build fails during installation

### ISSUE THREAD

**Issue by nicholasglazer** [zcoinofficial/zcoin#20]
Have this error: 
![photo_0162931327nbtylv](https://cloud.githubusercontent.com/assets/7410355/19520480/f14dcdb6-95ff-11e6-8787-f3d3c88b7639.jpg)

Arch Linux x64

**Comment by TimurKiyivinski** [comment]
I've submitted a package to the AUR. Can you test the build with that and see if it still fails to determine if it's a dependency issue?
https://aur.archlinux.org/packages/zcoin-git/

**Comment by nicholasglazer** [comment]
Seems like I missed  `boost` package. Good job, thanks for contributing to Arch community.

**Comment by TimurKiyivinski** [comment]
Good to know, perhaps issue can be closed now.
