### ISSUE TITLE
New protocol 90025 not detected

### ISSUE THREAD

**Issue by azilber** [zcoinofficial/zcoin#210]
Hi,

   I have a znode (version 130602) running with protocol 90025.  My desktop wallet sees it as running protocol 90024, along with a bunch of other znodes that are running 90025 but the wallet sees it as 90024.

The znode shows them as 90025.  There is some discrepency between getpeerinfo and what is reported in the znode synchronization.

**Comment by reubenyap** [comment]
This was a temporary workaround. This is because updating protocol number on our Znode system requires a rebroadcast which resets queue which was undesirable. This is because we don't utilize the sporks system in Dash. We are looking into a way to do this without interrupting payments.
