### ISSUE TITLE
Document Zcoin Multisig support

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#217]
Zcoin has the same multi sig support as Bitcoin P2SH. Their addresses start with 3 or 4 if I'm not mistaken. To document this properly.

**Comment by yura-pakhuchiy** [comment]
https://github.com/kp0z/2-of-2-zcoin-multisig

**Comment by yura-pakhuchiy** [comment]
btw, an easy way to use multisig is to use electrum. works even with trezor. have not tested with ledger, but should work as well
