### ISSUE TITLE
Fix Testnet for main branch (non MTP)

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#234]
Consensus parameter for testnet (non MTP) has a buggy serial check that causes version 13.6.6 not to sync past 60534 on master testnet.

To fix this in next release.

**Comment by riordant** [comment]
Further issues with testnet (will add more as I find them):
`IsBlockchainSynced` function in `znode-sync.cpp` does not properly update at the chain tip on testnet/regtest.

**Comment by reubenyap** [comment]
This is because not enough testnet znodes I believe. 

---- On Fri, 10 Aug 2018 23:37:00 +0800 notifications@github.com wrote ----

Further issues with testnet (will add more as I find them):
IsBlockchainSynced function in znode-sync.cpp does not properly update at the chain tip on testnet/regtest.

**Comment by riordant** [comment]
Potentially, but as it's a general function for seeing whether the chain is synced it should be fixed anyway
