### ISSUE TITLE
Add signatures to binaries and other OS versions

### ISSUE THREAD

**Issue by ManfredKarrer** [zcoinofficial/zcoin#24]
I think a privacy centric platform should do the small extra step to add pgp signatures of the binaries. To have OSX and linux versions would be good as well. I saw that there is a OSX version from another contributor, but that means to build up trust to another unknown source. Many people (like me) are not willing to invest more time if they only quickly want to try it out.

**Comment by nopslide** [comment]
well, it didn't come from me. most thing i can do is ask him sign it.

**Comment by aizensou** [comment]
good suggestion, @ManfredKarrer. We will take this approach from now on.
