### ISSUE TITLE
Try to enable ZSTD for Tor

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#248]
Right now it seem like it is disabled due to it build successfully. On the system that have zstd installed it will fail in the linking state due to unresolved symbols for zstd (which can be workaround by passing `--disable-zstd` to `src/tor`). We may try to update Tor to the latest version to see if they already fixed this issue. If it still does not work, we might try to fix by ourself.

Related issue: https://github.com/zcoinofficial/zcoin/issues/193#issuecomment-416519201

**Comment by reubenyap** [comment]
I think for the moment let's go with 1. 3, will be revisited later.

**Comment by ultimaweapon** [comment]
Don't forget to test it with a node that does not have ZSTD enable to see if it backward compatible.

**Comment by ultimaweapon** [comment]
If we enable ZSTD then we should enable LZMA too. But before going into this we should understand what Tor use LZMA and ZSTD first to see if it fit in our usage.
