### ISSUE TITLE
OSX out of memory

### ISSUE THREAD

**Issue by ManfredKarrer** [zcoinofficial/zcoin#25]
The OSX binary causes an alert that there is no memory for the system available anymore. My MAC has 12GB RAM so that is quite a lot. In the activity manager I saw ZCoin consumes > 2GB which  is very high but event that should not cause that problem. It happens at first startup.

**Comment by nopslide** [comment]
@sschepis please look at this issue

**Comment by mtford90** [comment]
Yep - unusable for me. Uses my entire 16gb of memory on OSX sierra bringing the system to a halt
