### ISSUE TITLE
Splash screen is blurry on Linux HiDPI screen

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#253]
I guess this happened on Windows and macOS too.

![Blurry splash screen](https://user-images.githubusercontent.com/3048307/45532120-0dce8200-b81d-11e8-933b-19c0cf91b870.png)

**Comment by catchingknives** [comment]
Path to image: ![https://github.com/zcoinofficial/zcoin/blob/master/src/qt/res/images/splash.png](https://github.com/zcoinofficial/zcoin/blob/master/src/qt/res/images/splash.png)

**Comment by ultimaweapon** [comment]
No need to invest time on this issue since we are going to move to new GUI (new GUI does not have this splash screen).
