### ISSUE TITLE
test_bitcoin should be build only when executing make check

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#261]
Right now it build when we run `make`. This will reduce a lot of build time when we don't need to build unit tests. What we need to do is changing `bin_PROGRAMS += test/test_bitcoin` in `src/Makefile.test.include` to `check_PROGRAMS` instead (consult [document](https://www.gnu.org/software/automake/manual/html_node/Scripts_002dbased-Testsuites.html#Scripts_002dbased-Testsuites) for more details). This should also prevent `test_bitcoin` to install when we execute `make install` too.

We may also rename `test_bitcoin` to `test_zcoin` too :)

**Comment by ultimaweapon** [comment]
Even changing `bin_PROGRAMS` to `check_PROGRAMS` still build unit tests (normally it will not). Look like there is some weird rules in build script that need to look on.

**Comment by riordant** [comment]
I'm not sure if I agree with this. I would prefer the behaviour that after altering files in `src/test`, they can continue to be built with `make` rather than `make check`. It's straightforward to disable building tests altogether with the `ENABLE_TESTS` flag.

**Comment by ultimaweapon** [comment]
The main issue is it build test by default when run `make` which is not expected behavior. Most GNU Autotools project will build test only when requested by user (which is `make check`). Another issue is it also install `test_bitcoin` binary too, which should not. We may leave the current behavior and change the default value for `ENABLE_TESTS` to not build test by default.
