### ISSUE TITLE
Should I upgrade to 0.13.6.7?

### ISSUE THREAD

**Issue by lcgogo** [zcoinofficial/zcoin#268]
Now my node is 0.13.6.3 and I see your release notes said 0.13.6.7 is a Mandatory update.

Upgrade before Block 107246.

However, my node has more blocks than 107246 and the hash is same as your offical block explorer https://insight.zcoin.io/.

Should I upgrade to 0.13.6.7?

**Comment by ultimaweapon** [comment]
Yes, you should upgrade to prevent your local fork.
