### ISSUE TITLE
We should show a progress when running unit tests in src/test/test_bitcoin via make check

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#270]
Right now it silently. The problem is this one is taking so long to complete. It will be great if we also can show what tests that fail. Consult [this](https://www.boost.org/doc/libs/1_68_0/libs/test/doc/html/boost_test/test_output/test_output_progress.html) and [this](https://www.boost.org/doc/libs/1_68_0/libs/test/doc/html/boost_test/utf_reference/rt_param_reference/log_level.html) for how to.

**Comment by FreakyMaryk** [comment]
We already added Jenkins build which are showing the process.

**Comment by ultimaweapon** [comment]
No it not show progress for unit tests. It show only what step it is currently on, not test case it is currently run.

**Comment by qashban4** [comment]
Work on this issue when we have time.

**Comment by ultimaweapon** [comment]
If we want to stick with Bitcoin codebase we better not do this due to it will make the upgrade harder.
