### ISSUE TITLE
Upgrade Tor to latest version

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#273]
See @reubenyap comment at https://github.com/zcoinofficial/zcoin/pull/249#issuecomment-427244780

**Comment by reubenyap** [comment]
https://blog.torproject.org/new-release-tor-0348-also-other-stable-updates-02917-03212-and-03310

Latest TOR release is 0.3.4.8

**Comment by reubenyap** [comment]
Latest release now is 0.3.5.8. Let's make sure this is reflected in Trello.

**Comment by ultimaweapon** [comment]
Card created.

**Comment by reubenyap** [comment]
Latest version 0.4.0.5 now is https://blog.torproject.org/new-release-tor-0405. @riordant will be taking it.

**Comment by reubenyap** [comment]
@levonpetrosyan93 has done some work on it and will be completing soon.

**Comment by levonpetrosyan93** [comment]
Yes, Itis working, PR wil be  created today.

**Comment by reubenyap** [comment]
#525
