### ISSUE TITLE
Automatic create Docker image and push it to docker hub when tag is created

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#277]
Currently there is only one repository: https://hub.docker.com/r/zcoinofficial/zcoind

**Comment by ultimaweapon** [comment]
We need this to prevent this issue in the future: https://github.com/zcoinofficial/zcoin/issues/306

**Comment by FreakyMaryk** [comment]
@ultimaweapon is it actual?

**Comment by ultimaweapon** [comment]
Yes.

**Comment by qashban4** [comment]
@ultimaweapon to work on this after finishing ZTM

**Comment by thebevrishot** [comment]
Script to create docker image and push to docker hub is added to Jenkins CI by @ultimaweapon
