### ISSUE TITLE
Make checklist of test cases before merge/release

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#287]
**Before merge changes to master we should verify, that all functionality is fine**
Should be list of checks, like:
**GUI**
* Send to one user
  - with transaction fee
  - with default fee
  - with valid/invalid amount
* Send to multiple users
  - with transaction fee
  - with default fee
  - with valid/invalid amount
* Receive
  - valid (all fields are correct)
 - invalid (some combinations)
* Zerocoin mint
* Zerocon spend
* Transactions
* Znode

--------
* Settings
  - Encrypt wallet
  - Options
  - Help 
     + Debug window
     + Command-line options
  - File
     + ...

**Comment by reubenyap** [comment]
To test fresh sync and also wallet reindex.
Zerocoin spends both first party and third party.
Backup wallet
To test in wallet mining? setgenerate true
getblocktemplate still works?

May need @psolstice or @mfrankovi  feedback as well
