### ISSUE TITLE
Never use std:: threading functions, use boost:: instead

### ISSUE THREAD

**Issue by psolstice** [zcoinofficial/zcoin#295]
We always use boost for several reasons
1. It is the way bitcoin uses it as of version 0.13
2. Consistency across code
3. There are problems building and running program with mingw. To compile it user has to explicitly choose posix alternative (`sudo select-alternatives …`) which is not default one

One offending file is `threadinterrupt.h`
Please change it to boost

EDIT: I understand that now bitcoin switched to std:: but for the time being we need to use boost::

**Comment by marpme** [comment]
or start rebasing to the newest bitcoin to get rid of boost at all?

**Comment by psolstice** [comment]
with rebase going on it stopped being an issue
