### ISSUE TITLE
Proposal on Governance, Voting and Zerocoin

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#296]
I have been thinking of governance for a long while and also the Zerocoin anonymity sets. This is something maybe we can do in 2019.

So it's clear that having 1 Znode = 1 vote is not good since it has a lot of centralization of decision making powers in only whales. This is also compounded with the fact of founder's reward.

Instead I was thinking of using Zerocoin mints to entitle to votes proportionate to the value of the coins minted. The main issue is we don't want to tie the mints together or have people expose themselves so the votes should be cast in a delayed fashion and with dandelion routing would also not expose the voter's IP.

This will solve two problems.

1. Now everyone with Zcoin can participate not just whales as in the traditional masternode voting system which in most coins is rigged anyway by large dev holdings. Masternode holders cannot bully their way since they won't want to break up their nodes. They have to weigh the power of voting vs owning a masternode making it more egalitarian.
2. Will incentivize people to keep Zerocoins minted to get voting rights and increase anonymity sets naturally.

We can implement this as a way to do voting but not on funding yet as we don't want to rock the reward economics (but will be done perhaps when founder's reward ends).

Some other ideas to reduce voter apathy is when we do have 'project funding', that if people apply for funding, part of the funding goes to the people who voted but need to figure a way to do this without exposing the owners of the mints.

Appreciate everyone's thoughts on this.

**Comment by reubenyap** [comment]
I think the main issue with this is that you cannot tell which mint has been spent or not? Which means someone can remint and spend the same coin several times for multiple votes. Or can a hash of the secret be exposed or some way to prove that the mint has not been spent yet.

Would need @psolstice feedback on this and how it affects anonymity.

**Comment by psolstice** [comment]
General idea is great. One possibility is to create a special kind of spend which then locks the funds until the voting is done (no double-spends here as serials are revealed). By the end of the voting everything is reminted with new serials and goes back to the original owner.

For example when voting owner can presents a public key which is then used to encrypt reminted coin's parameters so only the owner can later reclaim it.

Seems feasible to me.

**Comment by reubenyap** [comment]
The mints are still indistinguishable from other mints yes?

**Comment by psolstice** [comment]
I'm talking about regular mints here so yes
for my sheme
Pro:
  can be made using few changes to current building blocks of zcoin
Con:
  vote is a spend (large, subject to spends/block limit)

**Comment by rloomba** [comment]
Awesome idea @reubenyap!

> Masternode holders cannot bully their way since they won't want to break up their nodes. They have to weigh the power of voting vs owning a masternode making it more egalitarian.

Is breaking up a node a huge disincentive for node owners? Let's say that someone proposes to increase the masternode reward by 50% and take away reward from the miners. Wouldn't most masternode owners be incentivized to break up their node and sacrifice a payout to vote, knowing that this sacrificed payout will yield higher ROI in the long run? I guess this could be generalized as: anytime a vote has more expected value than a znode payout + time/effort to break/restart node, it would be economically worthwhile.

I'm trying to offer some solutions to this. Time locking the coins after voting could work, but that would create some weird game theory scenarios.

**Comment by reubenyap** [comment]
Ongoing discussion here:
https://forum.zcoin.io/t/zcoin-governance-and-development-past-4-years/26
