### ISSUE TITLE
zcoin 0.13.7.1 make check failed

### ISSUE THREAD

**Issue by lcgogo** [zcoinofficial/zcoin#302]
make check has followed error.

In file included from ./src/or/or.h:31:0, from src/test/test_workqueue.c:6: /usr/include/sys/fcntl.h:1:2: warning: #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> [-Wcpp] #warning redirecting incorrect #include <sys/fcntl.h> to <fcntl.h> ^~~~~~~ CCLD src/test/test_workqueue PASS: src/test/test_workqueue PASS: src/test/test_keygen.sh PASS: src/test/test_key_expiration.sh CC src/test/test_timers-test-timers.o CCLD src/test/test-timers PASS: src/test/test-timers SKIP: src/test/fuzz_static_testcases.sh PASS: src/test/test_zero_length_keys.sh PASS: src/test/test_workqueue_cancel.sh PASS: src/test/test_workqueue_efd.sh PASS: src/test/test_workqueue_efd2.sh PASS: src/test/test_workqueue_pipe.sh PASS: src/test/test_workqueue_pipe2.sh PASS: src/test/test_workqueue_socketpair.sh PASS: src/test/test_ntor.sh PASS: src/test/test_hs_ntor.sh SKIP: src/test/test_bt.sh ============================================================================ Testsuite summary for tor 0.3.4.5-rc-dev ============================================================================

TOTAL: 18

PASS: 16

SKIP: 2

XFAIL: 0

FAIL: 0

XPASS: 0

ERROR: 0

============================================================================ make[4]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src/tor' perl ./scripts/maint/checkSpace.pl -C 
./src/common/.[ch] 
./src/or/.[ch] 
./src/test/.[ch] 
./src/test//.[ch] 
./src/tools/.[ch] make[3]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src/tor' make[2]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src/tor' make[2]: Entering directory '/zcoin-src/zcoin-0.13.7.1/src' make check-TESTS check-local make[3]: Entering directory '/zcoin-src/zcoin-0.13.7.1/src' make[4]: Entering directory '/zcoin-src/zcoin-0.13.7.1/src'

FAIL: test/test_bitcoin

Testsuite summary for Zcoin Core 0.13.7

TOTAL: 1

PASS: 0

SKIP: 0

XFAIL: 0

FAIL: 1

XPASS: 0

ERROR: 0

============================================================================ See src/test-suite.log Please report to https://github.com/zcoinofficial/zcoin/issues ============================================================================ make[4]: *** [Makefile:11492: test-suite.log] Error 1 make[4]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src' make[3]: *** [Makefile:11600: check-TESTS] Error 2 make[3]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src' make[2]: *** [Makefile:11699: check-am] Error 2 make[2]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src' make[1]: *** [Makefile:11384: check-recursive] Error 1 make[1]: Leaving directory '/zcoin-src/zcoin-0.13.7.1/src' make: *** [Makefile:688: check-recursive] Error 1

**Comment by lcgogo** [comment]
I run ./src/test/test_bitcoin manually and meet followed issue:

2018-10-25 08:59:03 Loading master transactions database: OK
2018-10-25 08:59:03 Loading fee cache database: OK
2018-10-25 08:59:03 Loading fee history database: OK
2018-10-25 08:59:03 Loading persistent state: NONE (no usable previous state found)
2018-10-25 08:59:03 Exodus balance: 0.00000000 EXODUS
2018-10-25 08:59:03 Exodus initialization completed
Balance before 0
Balance after 150 blocks: 200000000000
unknown location(0): fatal error in "mtp_transition": memory access violation at address: 0x00000000: no mapping at fault address
test/mtp_trans_tests.cpp(123): last checkpoint

*** 1 failure detected in test suite "Bitcoin Test Suite"
test_bitcoin: /usr/include/boost/thread/pthread/condition_variable_fwd.hpp:81: boost::condition_variable::~condition_variable(): Assertion `!ret' failed.
Aborted (core dumped)

**Comment by riordant** [comment]
@mfrankovi Seems to be an MTP related test.

**Comment by a-bezrukov** [comment]
Should be fixed now. I'll close it after verification on a new build.

**Comment by ultimaweapon** [comment]
Still failed but with a different location.

```
test/rpc_tests.cpp(40): error: in "rpc_tests/rpc_rawparams": check tableRPC[strMethod] has failed
unknown location(0): fatal error: in "rpc_tests/rpc_rawparams": memory access violation at address: 0x00000040: no mapping at fault address
test/rpc_tests.cpp(40): last checkpoint

*** 2 failures are detected in the test module "Bitcoin Test Suite"
```

**Comment by ultimaweapon** [comment]
I will take a look on latest error.

**Comment by ultimaweapon** [comment]
Look like the reason it fail because I apply only one commit #305. It need to apply both commits.

Also already tried on the latest master and no any errors. So I will close this.
