### ISSUE TITLE
Outdated zcoind version at Docker image hub

### ISSUE THREAD

**Issue by asluchevskiy** [zcoinofficial/zcoin#306]
Hi,

Zcoind image at https://hub.docker.com/r/zcoinofficial/zcoind/tags/ is outdated.
But docker installation from the image hub is described in the Readme file as a default approach instead building image from source.

Pleas, update image at hub, or describe in Readme file building from the source process.

**Comment by ultimaweapon** [comment]
Hi,

Thank you for reporting! We need this issue https://github.com/zcoinofficial/zcoin/issues/302 to be fixed first since it prevent docker image from building.

**Comment by ultimaweapon** [comment]
Docker hub now contains the latest release.
