### ISSUE TITLE
To look into protection mechanisms of 51% attacks

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#320]
One of the drawbacks of ASIC resistant algorithms are that they are arguably more susceptible to rented hashpower attacks as we have seen with Vertcoin though that was exacerbated with Lyra2RE ASICs rather than just pure GPU power.

As a coin with a masternode system, [Chainlocks](https://github.com/dashpay/dips/blob/master/dip-0008.md) offer an interesting solution to this which requires both masternodes and miners to collude to do a 51% attack.

Alternate solutions exist such as[ punishing delayed block submissions](https://www.horizen.global/assets/files/A-Penalty-System-for-Delayed-Block-Submission-by-ZenCash.pdf) but alone do not solve the issue.

This thread is meant to examine the pros and cons of incorporating 51% attack protections and to evaluate these schemes.

**Comment by leto** [comment]
The Komodo project has a form of 51% attack prevention called delayed-Proof-Of-Work (including automatic double spend prevention) which is documented here: 

https://github.com/leto/mastering_komodo_dpow/blob/master/mastering_komodo_dpow.md

It sends block hash data from your coin to Bitcoin itself, and dynamically adds checkpoint blocks based on blocks that have been "notarized". New consensus rules prevent nodes from disconnecting notarized blocks or re-organizing them away. Currently it protects KMD, HUSH, GAME, CHIPS, EMC2, VRSC and dozens of KMD asset chains from these attacks: http://notarystats.com/

**Comment by reubenyap** [comment]
We are probably going ahead with Chainlocks at this point in time. I'm not in favor of using dPOW as ideally I don't want to be reliant on any other chain for our security, even if it's Bitcoin.

Personally although Bitcoin is arguably the safest PoW coin at the moment, it is also the coin that has the most value and incentive to disrupt. We have to consider that as a real possibility if we believe that cryptocurrencies are truly changing that people will try to harm it. Although I believe Bitcoin is here to stay, we shouldn't take that for a fact and for granted.
