### ISSUE TITLE
RPC mint operations not shown in GUI after calling

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#325]
Steps to reproduce in tesnet:
(You need coins to mint)
1) open RPC
2) enter 'mintzerocoin 1'
Expected result: transaction successfully added, operation for mint is shown in UI
Actual:  transaction successfully added, operation for mint is NOT shown in UI. You can see it only after restart

**Comment by riordant** [comment]
This was fixed in https://github.com/zcoinofficial/zcoin/commit/0aef4a9fab8208c01414bdf169b2e72feb71dfe1
