### ISSUE TITLE
0.13.7.5 make check failed

### ISSUE THREAD

**Issue by lcgogo** [zcoinofficial/zcoin#328]
Hi, I use master branch and build. I use ubuntu 16.4
The make check failed like below

make[3]: Leaving directory '/root/zcoin-master/src/tor'
make[2]: Leaving directory '/root/zcoin-master/src/tor'
make[2]: Entering directory '/root/zcoin-master/src'
make[3]: Entering directory '/root/zcoin-master/src/secp256k1'
make[3]: Leaving directory '/root/zcoin-master/src/secp256k1'
make  check-TESTS check-local
make[3]: Entering directory '/root/zcoin-master/src'
make[4]: Entering directory '/root/zcoin-master/src'
make[5]: Entering directory '/root/zcoin-master/src/secp256k1'
make[5]: Leaving directory '/root/zcoin-master/src/secp256k1'
../build-aux/test-driver: line 107: 28309 Aborted                 (core dumped) "$@" > $log_file 2>&1
FAIL: test/test_bitcoin
============================================================================
Testsuite summary for Zcoin Core 0.13.7
============================================================================
# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See src/test-suite.log
Please report to https://github.com/zcoinofficial/zcoin/issues
============================================================================
Makefile:11059: recipe for target 'test-suite.log' failed
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory '/root/zcoin-master/src'
Makefile:11165: recipe for target 'check-TESTS' failed
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory '/root/zcoin-master/src'
Makefile:11264: recipe for target 'check-am' failed
make[2]: *** [check-am] Error 2
make[2]: Leaving directory '/root/zcoin-master/src'
Makefile:10952: recipe for target 'check-recursive' failed
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory '/root/zcoin-master/src'
Makefile:688: recipe for target 'check-recursive' failed
make: *** [check-recursive] Error 1

The test-suite log is attached.

[test-suite.log](https://github.com/zcoinofficial/zcoin/files/2674517/test-suite.log)

**Comment by justanwar** [comment]
How much RAM does the Ubuntu system has? MTP mining test has a high memory requirement, as per #312

**Comment by riordant** [comment]
Available memory is definitely the issue here. I have tried to run `make check` on the latest release with 16gb of RAM with no issues. What is your available memory?

**Comment by reubenyap** [comment]
Due to no reply closing this issue.
