### ISSUE TITLE
Znode weird crash log

### ISSUE THREAD

**Issue by oti-dev** [zcoinofficial/zcoin#329]
> 2018-12-12 20:49:52 connect() to [2601:242:4200:def1:20af:3c7c:b337:3dcf]:8168 failed: Network is unreachable (101)
> 2018-12-12 20:50:10 CZnodeMan::CheckAndRemove
> 2018-12-12 20:50:10 CZnodeMan::CheckAndRemove -- Znodes: 4209, peers who asked us for Znode list: 0, peers we asked for Znode list: 0, entries in Znode list we asked for: 0, znode index size: 4215, nDsqCount: 0
> 2018-12-12 20:50:10 CZnodePayments::CheckAndRemove -- Votes: 50501, Blocks: 5267
> 2018-12-12 20:51:11 CZnodeMan::CheckAndRemove
> 2018-12-12 20:51:11 CZnodeMan::CheckAndRemove -- Znodes: 4209, peers who asked us for Znode list: 0, peers we asked for Znode list: 0, entries in Znode list we asked for: 0, znode index size: 4215, nDsqCount: 0
> 2018-12-12 20:51:11 CZnodePayments::CheckAndRemove -- Votes: 50501, Blocks: 5267
> ^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
> (END)

My znode (version 13705) crashed and that's how the logs end looked like. Any idea what it is?

**Comment by riordant** [comment]
@oti-dev Have you received the same issue as of the newer versions?

**Comment by oti-dev** [comment]
No, I haven't.
