### ISSUE TITLE
setLockedCoins in wallet.h not saving between runs (Coin Control Features - Settings Don't Save)

### ISSUE THREAD

**Issue by bitofdon** [zcoinofficial/zcoin#332]
The `setLockedCoins` list in `wallet.h` is meant to be a persistent list for the storage of coins locked by the user. This has been tested both the GUI and via the `lockunspent` RPC functions, in both cases there is no persistence of the objects added to the list between runs.

Original post:
When enabling Coin Control Features and you go to lock unspent coins:

Send > Inputs > right click on address you want to "Lock unspent" 

The "Lock unspent" never saves after restarting the wallet. However, Znode addresses can be seen/remain locked.

wallet v0.13.7.5

**Comment by riordant** [comment]
@bitofdon I can replicate this issue, although Znode addresses also do not work for me. Znode addresses remain locked for you on a restart?

**Comment by bitofdon** [comment]
@riordant that's odd, for me Znode addresses are always locked for me. Never had an issue with them in Coin Control Features not being locked.

**Comment by riordant** [comment]
@bitofdon : https://github.com/bitcoin/bitcoin/pull/1861
What this is saying is, the locked coins are not saved between runs of the wallet - it is not written to the database. In the case of Znodes, we have initialisation code which automatically locks all Znode collateral outpoints that are seen in the Znode config file, if they are valid. We do not have plans to make locking persistent between runs. As a result, I am closing this.
