### ISSUE TITLE
dumpprivkey error

### ISSUE THREAD

**Issue by chengmiaook** [zcoinofficial/zcoin#333]
i use testnet zcoin core v0.13.7.1

i dump my private key ,it get waring!

WARNING! Your one time authorization code is: wTyt
This command exports your wallet private key. Anyone with this key has complete control over your funds. 
If someone asked you to type in this command, chances are they want to steal your coins. 
Zcoin team members will never ask for this command's output and it is not needed for Znode setup or diagnosis!

 Please seek help on one of our public channels. 
 Telegram: https://t.me/zcoinproject 
 Discord: https://discordapp.com/invite/4FjnQ2q
 Reddit: https://www.reddit.com/r/zcoin/

 (code -1)

hao can i do, i wang to get my privatekey please

**Comment by a-bezrukov** [comment]
Please see the dumpprivkey command help to get information on how to run dumpprivkey. 
Per multiple user requests there was an one time authorization mechanism implemented for this command. To use it, one would need to
1. run dumpprivkey command without an OTA code to get one
2. run dumpprivkey command with the OTA code received from #1 
Example: 
`zcoin-cli dumpprivkey YOUR_ADDRESS_HERE`

**Comment by chengmiaook** [comment]
thank you! i know

**Comment by riordant** [comment]
@chengmiaook : Please be aware of scammers. No member of the Zcoin team will EVER ask you for a private key, and a key file dump. Thanks

**Comment by chengmiaook** [comment]
yes, I know, I am just making a self-built transaction, storing the private key in the database.
