### ISSUE TITLE
Help message lists wrong listening ports

### ISSUE THREAD

**Issue by christophersanborn** [zcoinofficial/zcoin#34]
The help message seen when running "./zcoind --help" lists the wrong default ports for -port option and -rpcport, creating confusion for users trying to learn how to run a secure full node.

The help message lists the default -port value as 8889, when in fact it appears the program listens on 8168.

The help message lists the default -rpcport value as 6888, when in fact it appears the program services rpc calls on port 8888.

**Comment by nopslide** [comment]
Thank you so much, I will change it

**Comment by aizensou** [comment]
Fixed
