### ISSUE TITLE
Multiple mint operation with coins to mint bigger than balance works unproperly

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#340]
Steps to reproduce:
The initial wallet balance is less than 1000000

1. Call from RPC mintmanyzerocoin  "{\"1\":1000000}"
2. Check transactions 

Actual: nothing happend and after reload can appeared
zcoin-qt: sync.cpp:125: void potential_deadlock_detected(const std::pair<void*, void*>&, const LockStack&, const LockStack&): Assertion `onlyMaybeDeadlock' failed.
Aborted (core dumped)

Expected: Should return some error in RPC about and should not be such problems with sync

**Comment by riordant** [comment]
Fixes added in https://github.com/zcoinofficial/zcoin/commit/eea46175cb07

**Comment by riordant** [comment]
Several updates to the function added in https://github.com/zcoinofficial/zcoin/pull/342

**Comment by riordant** [comment]
Fixed in https://github.com/zcoinofficial/zcoin/pull/342
