### ISSUE TITLE
Znode- "New Start Required" issue

### ISSUE THREAD

**Issue by dholliday5** [zcoinofficial/zcoin#346]
Znode status turned to "New start required" all of a sudden and is causing miss payments will there be an update to the wallet to fix this issue? Thanks!

**Comment by dholliday5** [comment]
Actually received payment toward the end of the day, so didn't miss a payment. But probably still need software  update to make status reflect its true state. Thanks!

**Comment by catchingknives** [comment]
The wallet sometimes shows this status even though it's not accurate. If you get `NEW_START_REQUIRED` in your wallet, always make sure to double check on your node. Details here:  https://github.com/zcoinofficial/zcoin/wiki/Znode-Diagnostics

**Comment by dholliday5** [comment]
Thanks
