### ISSUE TITLE
Transaction unconfirmed on regtest

### ISSUE THREAD

**Issue by viettienbk** [zcoinofficial/zcoin#347]
I started the zcoin regtest node and transfered coins to address success, but the transaction unconfirmed.
My command:
`zcoind -regtest -printtoconsole`
`zcoin-cli -regtest generate 103`
`zcoin-cli -regtest sendtoaddress TQUaq452SiAp9bGccoc8Dp7FSF3fgTfAW6  10`
`zcoin-cli -regtest generate 7`
`zcoin-cli -regtest gettransaction 83256b5e7d4d0481a6cfa70d2e921d6675923a6ebc7982658e610c631abfa15a`
But, I got result:
`{
  "amount": -10.00000000,
  "fee": -0.00019100,
  "confirmations": 0,
  "trusted": true,
  "txid": "83256b5e7d4d0481a6cfa70d2e921d6675923a6ebc7982658e610c631abfa15a",
  "walletconflicts": [
  ],
  "time": 1548819293,
  "timereceived": 1548819293,
  "bip125-replaceable": "unknown",
  "details": [
    {
      "account": "",
      "address": "TQUaq452SiAp9bGccoc8Dp7FSF3fgTfAW6",
      "category": "send",
      "amount": -10.00000000,
      "vout": 0,
      "fee": -0.00019100,
      "abandoned": false
    }
  ],
  "hex": "0100000001673e8766ba9819c4c88eee43f53941f6e533df0f027e153dd84c97bf51d5ee090000000048473044022014b984fffedc7974029c609e72b0776c8e513520dd87ca4691216c953b719eea02205843635e57969eddd6e6a71bf06d57b041b47b314210b02985e55d85da43225501feffffff0200ca9a3b000000001976a9149f200b67002c864e35fed562e810ead78c31831088ac6413d0b2000000001976a91411386dfb10d4fd700affddb8e29132fdc8f63c8088acce000000"
}`
The confirmations of transaction = 0. Pls help me

**Comment by FreakyMaryk** [comment]
@viettienbk Hello! I will try to help you and will check it for u.

**Comment by FreakyMaryk** [comment]
@viettienbk Sorry for delay! Just disable -dandelion=0 option and all be fine.

> {
>  "amount": 0.00000000,
>  "fee": -0.00100000,
>  "confirmations": 0,
>  "trusted": true,
>  "txid": "5ea14511758f5b9cf08bcbc22b015f0944d9f2498d9d2dfa7e7dcfa5aff8c16e",
>  "walletconflicts": [
>  ],
>  "time": 1551396355,
>  "timereceived": 1551396355,
>  "bip125-replaceable": "unknown",
>  "details": [
>    {
>      "account": "",
>      "address": "TL5rcaXY63iRtrNGMRQgTHjH4wfvpKt5og",
>      "category": "send",
>      "amount": -100.00000000,
>      "label": "",
>      "vout": 0,
>      "fee": -0.00100000,
>      "abandoned": false
>    },
>    {
>      "account": "",
>      "address": "TL5rcaXY63iRtrNGMRQgTHjH4wfvpKt5og",
>      "category": "receive",
>      "amount": 100.00000000,
>      "label": "",
>      "vout": 0
>    }
>  ],
>  "hex": "0100000003d0f47dbf681af906e531751b8befcff10bb6003062dde0c2073d5ee0fd3ad81f00000000474630430220260f527fe481902b5764bd1c84ef04cdc507e1d3f68e9a0d8f2eda35964f57c7021f788eace7068e8e064721c7ad8c09a95ae0c41062dff8a6c6d302a5ffbca79401feffffff484fcf96df2040f6d90320ee7c21e557efab8fa535c745c0c322dd10580c3cd30000000049483045022100966f2533e0fe09ded4c7f5fb5f41f987a9f521af64b05bfad73fb18d1432d05602204a9da7f2cef39cf8aabdfd96230d5ba3218394f7dfa62683e4dd79217d52e1ce01feffffff5f0adf4bbc17a7209f8362e9398e701df30082d15c936d0dafde479ddc4fbb1a0000000049483045022100c92d14967adabb8482930dcb404a492f51c007e5575ba8754bcb0bda3208149b02203b11e2e2ec406d9bc4fe1310b845fd293d0e06d7e99e52d91eddf07d13b94d3e01feffffff0200e40b54020000001976a9146ef3269f4f5a415bb390432be3a8ffc3a7a3780b88ac600d3477000000001976a914638cced71a0fe06ddfdef0f64b2e108da1d40efd88ac98000000"
> }
