### ISSUE TITLE
Investigate Flyclient Support for Zcoin

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#359]
Flyclient allows super-light clients for cryptocurrencies.
https://eprint.iacr.org/2019/226

Given the large header size of MTP, even with SPV, syncing headers can still be relatively long. Flyclient greatly reduces this.

To research on
a) How it affects Zerocoin/Sigma/Lelantus transactions
b) whether it rules out private tx sending
c) How easy it is to implement on Zcoin

**Comment by a-bezrukov** [comment]
We have 117564 headers of pre-mtp 80-byte size, which is 117564*80 = 8.97 MB of data. If we didn't change the header size in 5 years and keep the 5 mins as the block generation period, in 5 years it' will  be 60/5*24*365*5 = 525600 blocks more, which is 525600*180 = 90.26 MB of data more. In 5 years the total amount of data for SPV to work will be less than 100 MB.

**Comment by reubenyap** [comment]
Decided to KIV this as more urgent issues to deal with at the moment.

**Comment by TomaszWaszczyk** [comment]
Anyone works on that?
