### ISSUE TITLE
Gettransaction for spendzerocoin with address return invalid data

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#363]
Steps to reproduce:
1) Mint some coinst
2) Create spend to from rpc with coin and rcpt
3) spendzerocoin 1 TFfXrFRs4eJStyBL9dSoNTUXL1MZ2fCwq4

*Check gettransaction*:
gettransaction 8ccb5a17159ace3b8bfc8cd7c570bdd34179f147c0f9d7f4b9368ad4c1df638f

*Expected*: details for transaction should contains category with spend value

*Actual*: Amount is empty and details is empty.
But thr getrawtransaction 1 returns correct value

**Comment by psolstice** [comment]
Note: you cannot spend to your own address, there shouldn't be a private key in wallet associated with address. Hence the bug occurs when the spend transaction is watch-only
