### ISSUE TITLE
Qt Wallet v0.13.7.8 - Slow Loading Time, Wrong Transaction History

### ISSUE THREAD

**Issue by bitofdon** [zcoinofficial/zcoin#379]
**Zcoin-Qt: v0.13.7.8
OS: Linux, Mac, Windows**

- With the latest wallet update to 13.7.8 - wallet loading time has been extremely slow, across all operating systems

- Transaction history and their timestamps appear to have changed, are incorrect, or even [duplicates](https://imgur.com/a/i72FJOc)

These issues have been expressed by multiple users

**Comment by justanwar** [comment]
Please check latest release v0.13.7.10 and the accompanying release note for the fix.

**Comment by reubenyap** [comment]
This is resolved in 13.7.10 so am closing this issue.
