### ISSUE TITLE
https://bootstrap.zcoin.io/ snapshot has some error

### ISSUE THREAD

**Issue by lcgogo** [zcoinofficial/zcoin#382]
tar -zxf snapshot.tar.gz

gzip: stdin: unexpected end of file
tar: Unexpected EOF in archive
tar: Unexpected EOF in archive
tar: Error is not recoverable: exiting now

I downloaded twice. Each of them has untar issue like above.

wget https://bootstrap.zcoin.io/snapshot.tar.gz
--2019-04-27 10:29:25--  https://bootstrap.zcoin.io/snapshot.tar.gz
Resolving bootstrap.zcoin.io (bootstrap.zcoin.io)... 104.18.62.148, 104.18.63.148
Connecting to bootstrap.zcoin.io (bootstrap.zcoin.io)|104.18.62.148|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7488040960 (7.0G) [application/octet-stream]
Saving to: ‘snapshot.tar.gz’

snapshot.tar.gz              100%[============================================>]   6.97G  13.5MB/s    in 10m 3s

2019-04-27 10:39:29 (11.8 MB/s) - ‘snapshot.tar.gz’ saved [7488040960/7488040960]

**Comment by justanwar** [comment]
Fixed.

**Comment by 2ge** [comment]
bootstrap is not possible to download from anywhere. Please fix locations, either 502, 404 and so on
