### ISSUE TITLE
When you "Lock unspent" in coincontrol, the "Available amount to mint:" does not get updated.

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#416]

**Comment by riordant** [comment]
Technically that amount is available, it's just locked, it's the same situation with overall available balance. This is the same behaviour as in Bitcoin afaik. Therefore I don't think it should be changed. Thoughts @reubenyap @catchingknives ?

**Comment by catchingknives** [comment]
This is addressed in #426. Would keep this open till merged

**Comment by catchingknives** [comment]
Implemented in #439
