### ISSUE TITLE
Consensus/syncing issue

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#419]
[zcoin_stuck_51683_debug.log](https://github.com/zcoinofficial/zcoin/files/3186746/zcoin_stuck_51683_debug.log)
I left a new testwallet syncing through the night.
This morning it said fully synced, but upon restarting the wallet showed 2 weeks behind.
It was synced up to only to one node that appears to be stuck at block 51683.
This is a problem that has plagued zcoin for years, and I have resynced wallets from scratch over 10 times in the past and have many .zcoin, .zcoin-, .zcoin--, .zcoin---, etc directories to prove it.

**Comment by chileminer** [comment]
getchaintips shows that there are 5 wrong forks on testnet not including the nodes that I manually banned

**Comment by chileminer** [comment]
getchaintips a few hours ago had 25 entries!

**Comment by chileminer** [comment]
zcointest:~$ zcoin/src/zcoin-cli getchaintips | grep hash | wc -l
501
over 500 different chain tips now!

**Comment by chileminer** [comment]
There is another issue with consensus.   Whenever I mine from my wallet, with "setgenerate true" or solomine with a miner pointed at my wallet, it generates blocks really fast, but those blocks don't get propagated to the network or accepted by the network.   I can't tell which.

**Comment by catchingknives** [comment]
Now that you are on the correct chain, is this still an issue?

**Comment by chileminer** [comment]
What does "correct chain" mean?
You had said it was the chain with the most work, but clearly that is not the case for the chain we're currently on.

**Comment by chileminer** [comment]
It seems now that one of my wallets at block 54637 shows only 1 chaintip since I synced it from scratch.   Was that the goal of this manual intervention of rewinding the blockchain almost 10k blocks?    If that is the reason, my objection is that noone wants to do manual interventions IRL.    I've had around a dozen Zcoin wallets that wouldn't sync over the years, and sometimes when I would update the software it would still take multiple attempts and removing the old chain and starting over in order to get on the same chain as everyone else.    Manual interventions is NOT how to handle concensus problems.

**Comment by chileminer** [comment]
one of my testnet nodes became unsynced last night.  It has more PoW, but the rest of the network isn't following it.
Here is the one that is synced with testexplorer:

09:59:17
getinfo

09:59:17
{
  "version": 130801,
  "protocolversion": 90027,
  "walletversion": 130000,
  "balance": 6505.19995411,
  "blocks": 56761,
  "timeoffset": 0,
  "connections": 9,
  "proxy": "127.0.0.1:9050",
  "difficulty": 4.018908211602514e-05,
  "testnet": true,
  "keypoololdest": 1557780841,
  "keypoolsize": 99,
  "unlocked_until": 0,
  "paytxfee": 0.00001000,
  "mininput": 0.00001000,
  "relayfee": 0.00001000,
  "errors": ""
}

09:59:29
getblockhash 56761

09:59:29
36a14ee93de5724273e70e717a9f75186ea26cd51a51f31b95a39e877158e6be

09:59:37
getblock 36a14ee93de5724273e70e717a9f75186ea26cd51a51f31b95a39e877158e6be

09:59:37
{
  "hash": "36a14ee93de5724273e70e717a9f75186ea26cd51a51f31b95a39e877158e6be",
  "confirmations": 1,
  "strippedsize": 199350,
  "size": 199350,
  "weight": 199350,
  "height": 56761,
  "version": 536875008,
  "versionHex": "20001000",
  "merkleroot": "6c65d9a653a718b606b667ee698d3c2f4ff63311f11e5548de7ca0316555ba4f",
  "tx": [
    "6c65d9a653a718b606b667ee698d3c2f4ff63311f11e5548de7ca0316555ba4f"
  ],
  "time": 1559915371,
  "mediantime": 1559914904,
  "nonce": 187263,
  "bits": "1e613200",
  "difficulty": 4.018908211602514e-05,
  "chainwork": "000000000000000000000000000000000000000000000000000002f651eff5d0",
  "previousblockhash": "255e991e092b9a38d10cce4e32835cb2d663c13b49968f236fd4ca9f0cc4666f"
}


And this is the one that has forked off on it's own somehow:
09:58:39
getinfo

09:58:39
{
  "version": 130801,
  "protocolversion": 90027,
  "walletversion": 130000,
  "balance": 123.39643103,
  "blocks": 56772,
  "timeoffset": 58,
  "connections": 11,
  "proxy": "127.0.0.1:9050",
  "difficulty": 5.991920000795814e-05,
  "testnet": true,
  "keypoololdest": 1559357640,
  "keypoolsize": 100,
  "unlocked_until": 1569867671,
  "paytxfee": 0.00001000,
  "mininput": 0.00001000,
  "relayfee": 0.00001000,
  "errors": ""
}

09:58:47
getblockhash 56772

09:58:47
f46e804aaa1f7cfb98c5bd578324a9cb9c46fb7df2f079cb7f912851277cc32b

09:58:51
getblock f46e804aaa1f7cfb98c5bd578324a9cb9c46fb7df2f079cb7f912851277cc32b

09:58:51
{
  "hash": "f46e804aaa1f7cfb98c5bd578324a9cb9c46fb7df2f079cb7f912851277cc32b",
  "confirmations": 1,
  "strippedsize": 233372,
  "size": 233372,
  "weight": 233372,
  "height": 56772,
  "version": 536875008,
  "versionHex": "20001000",
  "merkleroot": "8c6290ca29cb592a9b00ca9789d378cf48bab13d924087b8c40b9d35919e0dbb",
  "tx": [
    "7c4fdb223a9b24023e96409f47948c84c05791e6840489b4e121f2a39b306c01", 
    "9b345411a41e986533e1babc4a8dcbe6c2cc6e89898d1449f08cb2c7332ed794"
  ],
  "time": 1559912296,
  "mediantime": 1559912196,
  "nonce": 11704,
  "bits": "1e4130e3",
  "difficulty": 5.991920000795814e-05,
  "chainwork": "000000000000000000000000000000000000000000000000000002f6520daabc",
  "previousblockhash": "71153ed59ec1dfa49e8691d786af0261470af6c4307dd1e0dc93113c6abfa19b"
}

**Comment by chileminer** [comment]
the one that was synced with textexplorer also forked at 57308
Had to invalidate block 57309 to get it synced back up.
if forked again, and I had to invalidate block 57484

**Comment by chileminer** [comment]
Forked again.
This time I minted 5999.9 and mined it into block #57499 with a cpuminer solomining on the same wallet.
no peers picked up block #57499.
Another strange thing I noticed when I minted it.   Usually a popup window shows up blank while it is busy minting and then when it is don it says something like sucessfully minted [OK].   This time the little window just went away and there was the transaction in mempool immediately.       I was watching mempool because I have seen delays before of almost a minute before it shows up in mempool.

**Comment by chileminer** [comment]
I stopped the miner and am waiting for someone to tell me what information they want to debug this.

**Comment by chileminer** [comment]
Looks like the rest of the network caught up and processed my big mint, but didn't accept my mining of it.   Maybe the miner I am using is bad?

**Comment by chileminer** [comment]
...and I did another big mint and forked again.  This time my mint didn't make it into testexplorer at least yet...

**Comment by chileminer** [comment]
It looks like blocks aren't being accepted by my v0.13.8.1-0c5d789-unk solomining, but they are just fine on my v0.13.8.1-8b7d49e-unk which I cloned and compiled this morning.

**Comment by FreakyMaryk** [comment]
@chileminer Hello!
Is it still actual for you?

**Comment by reubenyap** [comment]
Closing issue first. If it is a problem, please reopen.

**Comment by chileminer** [comment]
While I appreciate your reaching out to me, it's a bit late.   After Sebastian made false accusations against me and told me to stay off of testnet, I lost interest and haven't been on testnet much since.

Chile

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
