### ISSUE TITLE
setgenerate true initially works, and then does not

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#420]
When I first got my testnet wallet going, I was able to mine with "setgenerate true".   It mined until the 5/13 and then stopped.   Now if I do "setgenerate true" it does nothing, doesn't use much processor or memory.
I started a second testnet node on a 16 core server to see if I could get it to mine.   It did shortly.
It found 6 blocks and then stopped.   It won't mine anymore. Wallet from this second testnode attached

[wallet_testnet94.zip](https://github.com/zcoinofficial/zcoin/files/3188326/wallet_testnet94.zip)

**Comment by catchingknives** [comment]
You can verify if the wallet miner started by looking for a line like ```Running ZcoinMiner with x transactions in block``` in your debug.log. If that's there, but you don't see a line like ```Found a solution. Hash: ...```, you are mining but not finding blocks.

**Comment by chileminer** [comment]
![ZcoinMinerx16](https://user-images.githubusercontent.com/49484468/57895944-2ebbfc80-781c-11e9-8727-86ed7c25605c.gif)
you can also tell when it is mining it uses gobs of memory and cpus!
It doesn't mine most of the time.

**Comment by chileminer** [comment]
All of yesterday and today I had setgenerate true 8, and not once did I see Running ZcoinMiner in debug.log, nor earn any coins.     The lack of wallets mining could be contributing to testnet instability.

**Comment by chileminer** [comment]
I didn't mean to close it.  It is still a problem.

**Comment by catchingknives** [comment]
Did you check before mining that `znode winners` returns Znodes which are to be paid?

**Comment by reubenyap** [comment]
This works now already with all the Znodes online.
