### ISSUE TITLE
Mints stuck in "Pending" 

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#428]
I minted 1307.3 XZC while on my own fork.    Once I synced up the mints "Pending" did not... go away.

Status: 0/unconfirmed, not in memory pool
Date: 5/20/19 10:54
Total debit: -1303.70000000 XZC
Total credit: 1303.70000000 XZC
Transaction fee: -0.00011584 XZC
Net amount: -0.00011584 XZC
Transaction ID: 5e1b4e21186df030a2cd4d2d2eb1701bd55c86bd432d5817f1570b49d28c79a0
Output index: 0

![image](https://user-images.githubusercontent.com/49484468/58533464-9f68fe80-81b6-11e9-85ce-c18a6d090114.png)

**Comment by catchingknives** [comment]
This could be due to the delay introduced by Dandelion. Could you please try with `dandelion=0` in your zcoin.conf?

**Comment by chileminer** [comment]
The rest of the network rewound something like 10,000 blocks, so I have no peers with which to test this.

**Comment by catchingknives** [comment]
Is this still an issue?

**Comment by reubenyap** [comment]
Run with -zapwallettxes
