### ISSUE TITLE
Why isn't the net syncing up to the wallets that are on block 62???

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#435]
A few days ago I was told that if my testnet wallet was on anything other than block 52279 that I was on a fork.    At that time  testexplorer had 61832, mintpond 62,106.
I was told that the 52xxx chain had more work and that I could see for myself.

So with one of my wallets I recloned, recompiled, moved .zcoin off to the side  and synced up to the 52xxx chain by banning the peers with any later blocks.  
Also someone removed about 10k blocks from testexplorer and rewound that back to 52xxx.

But when I got synced up, I found that the 62xxx chain had more work:
for block 62721:   "chainwork": "000000000000000000000000000000000000000000000000000002f637baa875",
for block 52698:    "chainwork": "000000000000000000000000000000000000000000000000000002f50c512f8f",
so clearly there is more work on the longer chain.

So why the rewind of ~10k blocks?
I left one of my testnet wallets going, and it is at block 62721.   Why doesn't the rest of the testnet sync up to it?

**Comment by chileminer** [comment]
Another question.  I have had to resync my mainnet wallet more than a dozen times in the past few years and have a bunch of old .zcoin-- directories in backups some where.    Could this be related?
Could this be the cause of getchantips giving a multitude of results?    I saw 501 different tips once.

**Comment by chileminer** [comment]
140.82.11.194:18168 used to be on the 62xxx chain with one of my wallets, but now it is at block 54xxx.  Was this chain switch done manually like I did with my newest wallets?

**Comment by chileminer** [comment]
now test explorer has most of the month of may with no blocks.     Why was this done?

**Comment by reubenyap** [comment]
Please don't abuse Github for chat.
We changed consensus for some parameters like the Zcoin spend limits and hence it rewound. Correct version is always the one on testexplorer.
