### ISSUE TITLE
HTTP request failed: <url> malformed after a while solomining

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#453]
[2019-06-10 14:28:26] HTTP request failed: <url> malformed
[2019-06-10 14:28:26] HTTP request failed: <url> malformed
[2019-06-10 14:28:26] submit_upstream_work_mtp json_rpc_call failed

after a while (in the last case about 3 hourse) I get the above errors from cpuminer

**Comment by chileminer** [comment]
shutting down and restarting the wallet temporarily fixes it.    I'm on v0.13.8.1-8b7d49e-unk but it was a problem on earlier versions as well.

**Comment by chileminer** [comment]
Ran it for another hour and now I am getting 
HTTP request failed: Operation timed out after 30001 milliseconds with 0 bytes received
json_rpc_call failed, retry after 10 seconds

**Comment by FreakyMaryk** [comment]
@chileminer Is it still actual?

**Comment by djm34** [comment]
Hi, are you solo mining with cpuminer ?

**Comment by chileminer** [comment]
While I appreciate your reaching out to me, it's a bit late.   After Sebastian made false accusations against me and told me to stay off of testnet, I lost interest and haven't been on testnet much since.

Chile

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by FreakyMaryk** [comment]
@reubenyap @djm34  Should we close this? Or maybe continue investigation?

**Comment by chileminer** [comment]
I don't have time to look into it again.   Do what you think is best.

Sent with [ProtonMail](https://protonmail.com) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
