### ISSUE TITLE
Infection found: OSX.Trojan.Gen.2

### ISSUE THREAD

**Issue by sionsmith** [zcoinofficial/zcoin#454]
OSX Version 10.14.4

After downloading the the .dmg my norton finds and deletes the /Applications/Zcoin-Qt.app/Contents/MacOS/Zcoin-Qt file saying it has found: OSX.Trojan.Gen.2 

Please can someone verify this is actually an issue?? I'm a little confused why this would be found in the installed package.

**Comment by sionsmith** [comment]
@zcoinofficial @ultimaweapon @riordant Please can you look at this. I can provide you with the full scan transcript if needed.

Found in https://github.com/zcoinofficial/zcoin/releases/download/v0.13.7.10/zcoin-0.13.7.10-macos.dmg

**Comment by catchingknives** [comment]
This is an issue with all wallets that include an inbuilt mining component. As mining code is a popular payload of malware these days, many virus scanners also detect out wallet as such. 

In the case of the particular file you linked though, it appears that no scanner integrated into VirusTotal actually detects it as such. See [here](https://www.virustotal.com/gui/url-analysis/u-0d55f99a173b840a3aa41e68aa2d10188bb500d979d93b295e7e3cdcf285920f-1560233857/detection). Have you updated your signatures recently?

**Comment by catchingknives** [comment]
Sorry, I didn't use the site the right way it seems. Uploading the file leads to one detection as can be seen [here](https://www.virustotal.com/gui/file-analysis/ODk0YWUwOWFhNmNmMjFiYjhmNTJlMWQyNTYyN2EzMzE6MTU2MDIzNDA3NA==/detection). Yet, this is expected and will occur with every Bitcoin Core wallet-based release we make.

**Comment by AdmiralNeo** [comment]
<img width="1015" alt="Norton kills BTC-Downloads" src="https://user-images.githubusercontent.com/125405780/219349752-135231f8-44a6-4e0d-8915-0e6584c2b2f7.png">
Norton kills my official BTC Core Downloads - is there a solution?
