### ISSUE TITLE
Solomining causes a fork

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#455]
I have 2 wallets.  Both version v0.13.8.1-8b7d49e-unk, both run with -reindex since compiling them.
Had them synced up and up to testexplorer.   If I solomine on one with cpuminer, it forks and it's blocks are not accepted on testexplorer or the other wallet.   I mined until the rpcserver died.  

Then I solomined on the other one.  It's blocks weren't accepted on testexplorer either, so it is off on it's own fork now.
This looks to be readily repeatable.

**Comment by catchingknives** [comment]
I told you exactly what constitutes an issue and what doesn't. You choose to ignore it so I choose to close this.
