### ISSUE TITLE
Mining not valid Zcoin?

### ISSUE THREAD

**Issue by Carlo-C** [zcoinofficial/zcoin#48]
I have  mined Zcoin whit Windows wallet version 1.8 (https://github.com/zcoinofficial/zcoin/releases/), the coins is confirmed and I have this in my wallet; I send a coins to my wallet on Cryptopya and Novaexchange but the transactions not have effects; If I sendo coin to other my wallet have the same results: no transaction. Oly wen I send to myself have a transaction. I have checked transactions on https://zcoin.rocks/chain/ZCoin but not have retrieved any trace (by mining address, transaction ID..)
Previus I use 1.6 version.
Help me! 
Thanks

**Comment by aizensou** [comment]
As already explained in chat you're clearly mining on your own chain.
