### ISSUE TITLE
Memory Leak in RC1

### ISSUE THREAD

**Issue by azilber** [zcoinofficial/zcoin#495]
Have been running RC1 on testnet the past few days.

<img width="566" alt="Screenshot 2019-07-08 at 11 22 35 PM" src="https://user-images.githubusercontent.com/691270/60822101-68cfcc00-a1d7-11e9-8f50-e699f1f6bbe3.png">
Current zcoind use less than 500mb of resident ram.

**Comment by azilber** [comment]
<img width="556" alt="Screenshot 2019-07-08 at 11 40 24 PM" src="https://user-images.githubusercontent.com/691270/60823344-e72d6d80-a1d9-11e9-9ab6-4888257c541d.png">

Server time is currently Mon Jul  8 23:40:56 +08 2019

**Comment by a-bezrukov** [comment]
Hi @azilber 
This is normal when you `setgenerate true`, so please confirm that you didn't start mining. 
Thanks.

**Comment by azilber** [comment]
Nope, don't have setgenerate true.

`#----
rpcuser=XXXXXX
rpcpassword=XXXXXX
rpcallowip=127.0.0.1
#----
listen=1
server=1
daemon=1
logtimestamps=1
maxconnections=200
txindex=1
testnet=1
gen=1
genproclimit=1
#----
#znode=1
externalip=XX.XXX.XXX.XX:8168
#znodeprivkey=XXXXXXX
# seednodes
`

**Comment by azilber** [comment]
Oh no... gen=1?

**Comment by a-bezrukov** [comment]
`zcoin-cli getgenerate` to be sure. :)

**Comment by azilber** [comment]
```

./zcoin-cli getgenerate
true

```

RIP

That was it indeed.  Looks like MTP in action!  Glad it wasn't a memory leak!  Thank you!
