### ISSUE TITLE
Windows Wallet upgrade ignores previous install and config.

### ISSUE THREAD

**Issue by azilber** [zcoinofficial/zcoin#501]
I have the wallet installed in D:\Program Files\Zcoin

Installing previous versions, it picked up that file path for upgrades.

Version 13.8.1 wants to install to C:\Program Files\Zcoin

It does pickup the proper configs after install though.

**Comment by FreakyMaryk** [comment]
@azilber 
Hey, I will take a look on your issue

**Comment by a-bezrukov** [comment]
I could not find any traces in the code which would suggest that there was a mechanism for picking same install path as the previous installation had. 
Please feel free to reopen the issue if you manage to point to 2 versions which had such behavior.
