### ISSUE TITLE
Ledger Live native integration

### ISSUE THREAD

**Issue by ElvisPresly** [zcoinofficial/zcoin#509]
Hi. I wanted to ask that you added native support of Ledger Live.
There will be only positive sides:
- it is convenient to use in the uniform application
- to look through a portfolio
- additional software is not necessary
- level of the status Zcoin will grow

I found some information which has to help.
Ledger does not place the application on a paid basis now.

https://github.com/LedgerHQ/ledger-live-desktop/issues/1560
&
https://trello.com/c/v3rLhujF/111-how-to-request-a-feature-for-ledger-live

Thank You

**Comment by ElvisPresly** [comment]
Ledger Nano X + Mobile phone + Ledger Live = You are a super hero )

**Comment by catchingknives** [comment]
Ledger Live support is far from free. In fact the integration fee is outrageous an we are neither willing nor able to pay that amount of money for it.
