### ISSUE TITLE
Disk Read/Write Specs

### ISSUE THREAD

**Issue by gaia** [zcoinofficial/zcoin#513]
I am fine tuning the filesystem for running znodes and would like to know the size at which read/write operations occur.

I gather that most IO demand comes from R/W ops on the blocks/blkNNNNN.dat files.

Is this correct? If yes, **what is the ideal disk block size to reduce the IO overhead and increase performance on a system dedicated to running a znode?** I'd think something like 2MB, but these might be DB files with a smaller page size. **and are the write synchronous or asynchronous?**

thank you

**Comment by catchingknives** [comment]
Closed after discussion on Discord
