### ISSUE TITLE
znodelist full different on completely synced znodes

### ISSUE THREAD

**Issue by AdvancedStyle** [zcoinofficial/zcoin#524]
Have multiple synced znodes (v13.8.2) which are showing different results on the `znodelist full` command.

`znsync status` on both nodes is:

> {
>   "AssetID": 999,
>   "AssetName": "ZNODE_SYNC_FINISHED",
>   "Attempt": 0,
>   "IsBlockchainSynced": true,
>   "IsZnodeListSynced": true,
>   "IsWinnersListSynced": true,
>   "IsSynced": true,
>   "IsFailed": false
> }

But example of difference in `znodelist full`:

1st Znode shows:

>   "COutPoint(eda5962dc73c9e892caec92afdc69d2913486b5308618ac79eb13214f73a5770, 0)": "NEW_START_REQUIRED 90026 aHhnGgja6dMVRJgvY2uFj65WrXtkXBeWSc 1563008966 15106637 1562285868 176873 188.165.146.127:8168",

2nd Znode shows:

>  "COutPoint(eda5962dc73c9e892caec92afdc69d2913486b5308618ac79eb13214f73a5770, 0)": "           ENABLED 90026 aHhnGgja6dMVRJgvY2uFj65WrXtkXBeWSc 1563394188 15491859 1562285868 176873 188.165.146.127:8168",

I have tried running `znsync reset` but does not help, so have tried deleting **zncache.dat** and **znpayments.dat** also does not fix the issue.

**Comment by justanwar** [comment]
What is the output of `znode count all` for both nodes? 

This node shows up as `ENABLED` from my side.

**Comment by justanwar** [comment]
The output of the first node shows `1563008966` which corresponds to a last seen time of 13 July, while the second one shows `1563394188` which is the current time. Have you tried stopping `zcoind` on the first node, removing `zncache.dat` and `znpayments.dat` and start `zcoind` again?

**Comment by AdvancedStyle** [comment]
`znode count all`

1st node:

> Total: 5477 (PS Compatible: 1135 / Enabled: 1135 / Qualify: 909)

2nd node:

> Total: 5477 (PS Compatible: 4823 / Enabled: 4823 / Qualify: 4219)

Yes I have tried restarting zcoind and removing zncache.dat and znpayments.dat

**Comment by justanwar** [comment]
Both your nodes have `ENABLED` numbers that have quite a lot missing from them. I recommend doing the deletion process again until the `ENABLED` number is very close to the ones [https://znodemonitor.com/statistics](here) and [https://znodestatus.privex.io/](here).

Make sure that `zcoind` has terminated completely before deleting the two dat files since `zcoind` writes out to the files when exiting. If you delete them too early, it might still get written.

**Comment by AdvancedStyle** [comment]
Ok yes i think the zcoind process had not completely stopped before i deleted the *.dat files.
I did it again and this time it is working:

> Total: 5477 (PS Compatible: 5191 / Enabled: 5191 / Qualify: 4532)

**Comment by justanwar** [comment]
Closing this for now, feel free to reopen if necessary.
