### ISSUE TITLE
Wrong lock on znodelist.cpp causing crash

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#535]
From @psolstice's comments on Slack

src/qt/znodelist.cpp
void ZnodeList::updateNodeList()
{
    TRY_LOCK(cs_mnlist, fLockAcquired);
this is wrong critical section to lock
and the crash is occurring in this function
you'll need to lock mnodeman.cs I think
the cs_mnlist is not referenced anywhere else
I suspect that something happens in another thread while znode list is being copied in mnodeman.GetFullZnodeVector() call
diff --git a/src/znodeman.h b/src/znodeman.h
index 988002ba4..189a09c05 100644
--- a/src/znodeman.h
+++ b/src/znodeman.h
@@ -294,7 +294,7 @@ public:
     /// Find a random entry
     CZnode* FindRandomNotInVec(const std::vector<CTxIn> &vecToExclude, int nProtocolVersion = -1);
 
-    std::vector<CZnode> GetFullZnodeVector() { return vZnodes; }
+    std::vector<CZnode> GetFullZnodeVector() { LOCK(cs); return vZnodes; }
 
     std::vector<std::pair<int, CZnode> > GetZnodeRanks(int nBlockHeight = -1, int nMinProtocol=0);
     int GetZnodeRank(const CTxIn &vin, int nBlockHeight, int nMinProtocol=0, bool fOnlyActive=true);

**Comment by psolstice** [comment]
Fixed by #539
