### ISSUE TITLE
For legacy non-HD wallets, Zerocoin remint functions are disabled with Sigma

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#543]
For those having old wallets that do not have a HD seed, Sigma functionality is disabled meaning we cannot do Zerocoin remints as well.

To enable Sigma support for non-HD wallets and Zerocoin reminting feature but recommend migration to HD wallets.

**Comment by reubenyap** [comment]
@riordant assigned to this.

**Comment by riordant** [comment]
After discussion, recommended action is to have a warning to the legacy wallet user that they should use `dumpwallet` and `importwallet` into a fresh wallet, now that we have Zerocoin support for this.

**Comment by qashban4** [comment]
After checking with team.
That issue is covered by this PR: https://github.com/zcoinofficial/zcoin/pull/684
Will be closed once PR 684 is merged.
