### ISSUE TITLE
Sigma transaction size not being calculated correctly by coin control

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#562]
Bug reported by @goodc0re on Telegram

## Actual behaviour
Coin control is calculating the size of the Sigma spend transaction at 226 bytes and estimating fees based on that.
Actual is 1.4 kB which is calculated correctly on the confirmation screen.

![image](https://user-images.githubusercontent.com/22736605/62137205-26059d80-b318-11e9-8ba3-311fb6310f5e.png)

## Desired behaviour

Coin control for Sigma should calculate it based on Sigma spend size not regular transparent transactions.

## Steps to reproduce
- Go to coin control, inputs, select a mint.
- Go to spend, enter in an address and select the whole amount of the mint. Make sure Subtract fee from amount is selected.
- See the difference between Coin Control estimation and actual fee.

**Comment by FreakyMaryk** [comment]
@levonpetrosyan93 @reubenyap 
Verified. Can be closed
1) 
![image](https://user-images.githubusercontent.com/5564315/62352037-d689c200-b50f-11e9-88f1-92f440c93bfb.png)
2) 
![image](https://user-images.githubusercontent.com/5564315/62352056-e5707480-b50f-11e9-9836-ac7efbe34c2c.png)

**Comment by FreakyMaryk** [comment]
Waiting requested changes. And than re-check it again

**Comment by reubenyap** [comment]
pushed to 13.8.4
