### ISSUE TITLE
Implement common mechanism to calculate estimate fee for coincontrol and sigma GUI

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#569]
## Actual behaviour
This is for both **mint** and **spend** coin controls.

Actually we have **two** different mechanisms to calculate fee for coincontrol and for not, and it is possible to make common calculating. Instead of doing magic like this
https://github.com/zcoinofficial/zcoin/pull/568/files#diff-8224ea82bee334f4dae5ce96a62c463b

## Desired behaviour
* Common estimate fee calculation function, which calling in appropriate places instead of old functions with magic

* Should be RPC function for this internal one

**Comment by FreakyMaryk** [comment]
@reubenyap This task was dicussed with @ultimaweapon 
FYI @levonpetrosyan93

**Comment by reubenyap** [comment]
I think best to merge this issue with the original issue #562 since @levonpetrosyan93 has agreed to look into this.

**Comment by ultimaweapon** [comment]
Yes I agree. It may useful for other purpose too.

**Comment by levonpetrosyan93** [comment]
Guys If no concerns, let's close this for now.
