### ISSUE TITLE
Sigma spends do not show in transaction list when there is a remint until restart

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#572]
## Actual behaviour

When you do a Sigma spend and there's an auto remint for e.g.:
https://testexplorer.zcoin.io/tx/ca0ccfc72547fb933c956a12655300f2bf4707c40d1a967d9367470dba8a8ec6
it is not displayed in tx list.

However for Sigma spends that do not have remints such as
https://testexplorer.zcoin.io/tx/fe6bef3c15d07f7ee1336684b6dbe28a6445d146a75cdf2f5c7a2cd4d969967a
it appears fine.

However upon restarting the wallet, all transactions appear correctly.

Environment: **regtest**
Version: **v.0.13.8.3-01a50d393**

## Desired behaviour

All sigma spend transactions should appear immediately in tx list regardless whether there is a remint or not.

## Steps to reproduce
- Start from fresh wallet on regtest
- generate 401
- mint 20
- generate 6
![image](https://user-images.githubusercontent.com/5564315/62401622-acc2b080-b58c-11e9-8325-f09e3536d9a6.png)
- spend 3
![image](https://user-images.githubusercontent.com/5564315/62401650-c2d07100-b58c-11e9-89ec-bcdc6468738f.png)
![image](https://user-images.githubusercontent.com/5564315/62401663-d1b72380-b58c-11e9-93f5-343e2eb457fa.png)
- Look at transaction list.
![image](https://user-images.githubusercontent.com/5564315/62401676-de3b7c00-b58c-11e9-9026-38cbda8dd268.png)
- Restart wallet and see the transaction show up.
![image](https://user-images.githubusercontent.com/5564315/62401698-f4493c80-b58c-11e9-859c-2e888f44065d.png)

- Do a Sigma spend where you don't need to break up a denomination and just directly spend a denomination so no remints are required. This will appear on transaction list immediately (correct behaviour). 

PS Note sure if relevant but this wallet was a new wallet but imported a dumpwallet with importwallet. A rescan was triggered but not a reindex.
Will try reindex and see if it changes things.

**Comment by FreakyMaryk** [comment]
@reubenyap I believe that issue with reindex and rescan might be related to Tadhg fix you are right. We've been struggled with it. Need to add more automation tests on spends with remint.

**Comment by FreakyMaryk** [comment]
@reubenyap I was able to reproduce an issue with reindex

**Comment by riordant** [comment]
Fixed in https://github.com/zcoinofficial/zcoin/pull/581
