### ISSUE TITLE
Spend without 'Subtract fee from amount' check is not shown on transaction tab

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#573]
## Actual behaviour
Spend without 'Subtract fee from amount' check is not shown on transaction tab
Even for manyspend where one of operation with 'Subtract fee from amount' unchecked.

They are shown only after restart.

## Desired behaviour
Spend without 'Subtract fee from amount' check should be shown on transaction tab

Version where reproduce: **v.0.13.8.3-01a50d393**
Environment: **regtest**

## Steps to reproduce
1. Mint coins
![image](https://user-images.githubusercontent.com/5564315/62400018-7a15b980-b586-11e9-88b3-ef513221a71c.png)

2. Make spend without `subtract fee from amount`
![image](https://user-images.githubusercontent.com/5564315/62400065-a3cee080-b586-11e9-89b8-ec8336c20058.png)

3. Check transactions tab:
![image](https://user-images.githubusercontent.com/5564315/62400089-b517ed00-b586-11e9-8e67-a8cef3d64baa.png)

**Comment by riordant** [comment]
Fixed in https://github.com/zcoinofficial/zcoin/pull/581
