### ISSUE TITLE
Sigma unconfirmed spend with remint incorrectly shown on GUI after reindex

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#574]
## Actual behaviour
After reindex all spended coins became spendable and total are shown improperly also

## Desired behaviour
After reindex all spended coins should not be spendable again

Version where reproduce: **v.0.13.8.3-01a50d393**
Environment: **regtest**

## Steps to reproduce
- start from fresh wallet on regtest
- generate 401 block
- mint 20 and mint 20
- generate 6
- spend 3
![image](https://user-images.githubusercontent.com/5564315/62402409-4fc8f980-b590-11e9-87c1-1d23f1d17c1c.png)

- restart with reindex
![image](https://user-images.githubusercontent.com/5564315/62402419-5c4d5200-b590-11e9-8074-8ce562aac703.png)

- check 'Pending', 'Spendable', 'Total'

**Comment by FreakyMaryk** [comment]
@riordant I can see here, that if I will generate some blocks after reindex, spend will be still unconfirmed. And only after -rescan + block generated it will become confirmed.

**Comment by riordant** [comment]
@FreakyMaryk The balance will be properly updated after you rebroadcast any Sigma transactions.  The problem is that regtest does not automatically rebroadcast mempool transactions after reindex (mainnet does). It does rebroadcast after *another* restart though, so that is also possible.
