### ISSUE TITLE
CreateNewBlock: TestBlockValidity failed: bad-txns-zerocoin

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#575]
## Actual behaviour
CreateNewBlock: TestBlockValidity failed: bad-txns-zerocoin

## Desired behaviour
Should not appear

Version where reproduce: **v.0.13.8.3-01a50d393**
Environment: **regtest**

## Steps to reproduce
0. generate 401
1. mint 20
2. mint 20
3. generate 6
4. spend 3
5. restrart with -reindex
6. spend 3
7. encrypt wallet
8. restart with -reindex
9. generate 6 blocks
10. restart with -rescan
11. generate one more block
![image](https://user-images.githubusercontent.com/5564315/62403426-b13f9700-b595-11e9-98c9-ce1da647cd05.png)

**Comment by riordant** [comment]
Fixed in https://github.com/zcoinofficial/zcoin/pull/576
