### ISSUE TITLE
Wallet not syncing. No block source available...

### ISSUE THREAD

**Issue by miner8484** [zcoinofficial/zcoin#578]
## Actual behaviour
No block source available... 0 active connection(s) to Zcoin network
## Desired behaviour
Synchronizing with network
## Steps to reproduce
- backup wallet.dat
- Reinstall wallet from scratch

**Comment by reubenyap** [comment]
What wallet version please? Are you behind any sort of firewall and how long did you wait?

Could you attach your debug.log?

**Comment by miner8484** [comment]
This happened on v0.13.8.1. Reindexing didn't work it would stop at 821 866 or 1313 blocks. So I did fresh install of v0.13.8.2 with wallet.dat backup, but now it won't connect to Zcoin network to download blockchain and sync wallet. I'm not behind firewall since I've been using wallet for quite some time now.

**Comment by catchingknives** [comment]
If you only tried reindex on 0.13.8.1, please reindex again on 0.13.8.2

**Comment by miner8484** [comment]
@catchingknives I reinstalled wallet from scratch, which means I deleted blockchain from disk

**Comment by miner8484** [comment]
I clicked on "anonymous communication with Tor" and it triggered syncing process. Before installing fresh copy I also did zcoin related registry cleanup if it made any difference at all. When it's done I'll close this, if I get stuck again I'll let you know.
