### ISSUE TITLE
Display Correct Fee on Spend Dialogue

### ISSUE THREAD

**Issue by catchingknives** [zcoinofficial/zcoin#592]
## Actual behaviour
When you do a spend, a message is shown that says 0.05 XZC are given to miners. This isn't always true.

## Desired behaviour
As the client knows the exact fee at this time, it should be shown. 

## Steps to reproduce
Do any spend, see the message.

**Comment by levonpetrosyan93** [comment]
It always shows correct fee, only the message is confusing.
Message is this.
"Change will be reminted and amounts smaller than 0.05 will be paid as fees to miners."
Second part of the message can happen only when Subtract fee from amount is unchecked. 
We can print second part only for that case.
