### ISSUE TITLE
Add missing RPC

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/zcoin#595]
I think we missing some RPCs such 

- `exodus_getmintbalance <propertyId>`
- `exodus_listmints <propertyId>`

And we also need to add sigma mints amount of global state to rpc `exodus_getproperty` too.

- [x] Implementation [3]
- [x] Review [1]

**Comment by thebevrishot** [comment]
`exodus_listmints` to list all mints in wallet.

**Comment by ultimaweapon** [comment]
Blocked by #547 and #584.
