### ISSUE TITLE
Remove version number from README.md header

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#605]
Now we already have a badge to indicated the version of latest release. So I think we should remove the version number from the header (`Zcoin v0.13.8.3` to just `Zcoin`). One of the benefit is it will reduce the tasks for each release.

**Comment by catchingknives** [comment]
I agree

**Comment by reubenyap** [comment]
I agree

**Comment by thebevrishot** [comment]
make sense
