### ISSUE TITLE
Remove Travis status badge or repleace it with Jenkins one

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#606]
The reason is we no longer use Travis. For me we should remove it instead of replacing with Jenkins because it not useful. We already required all PR to be able to merge only if CI succeeded. So that mean the `master` branch is rarely to have errors.

**Comment by reubenyap** [comment]
I agree. Please implement thank you!

**Comment by riordant** [comment]
I take it this has been implemented? I can't see a Travis status badge in the README

**Comment by ultimaweapon** [comment]
Weird. I still see it.
![Untitled](https://user-images.githubusercontent.com/3048307/64404281-9cc75080-d0a5-11e9-9d49-f1ef4d9bc1b2.png)
