### ISSUE TITLE
Dump/Import wallet seems works incorrect with unconfirmed zerocoin mint and spend

### ISSUE THREAD

**Issue by FreakyMaryk** [zcoinofficial/zcoin#609]
## Actual behaviour
The list of zerocoin mint, spend , spentmint seems to be different to list before import dump wallet

## Desired behaviour
All this list should be same before and after import dump wallet.

## Steps to reproduce 
ENV: **Regtest**
1. I make mints and confirm them
2. I make spends and confirm them
3. I make mint and spends and not confirm
4. I make dump wallet
5. I remove wallet.dat
6. I import dump wallet
7. I chack mint list, spend list, unspentmint list
**I expect them to be matched to lists which I had before remove wallet.dat**
https://github.com/zcoinofficial/zcoin/pull/601

**Comment by riordant** [comment]
Mempool is discarded on a reimport with a new wallet. The test considers the unconfirmed keys also, that's why it fails. I have updated to fix this, along with the other test issues, as well as an issue with update of Sigma keys following import
