### ISSUE TITLE
Znode cli JSON parse errors with 0.13.8.3

### ISSUE THREAD

**Issue by anonGithubAcct** [zcoinofficial/zcoin#613]
## Actual behaviour
I'm seeing recently-setup nodes go down with a much higher frequency (often within 48 hours of getting them running again).
The only clear symptom I see is an error the zcoin-cli gives about an error while parsing JSON.  `zcoin-cli getinfo`, `zcoin-cli znsync status`, and `zcoin-cli znode status` all give the same eror parsing JSON (rather than any of the normal output from those commands).

## Desired behaviour
The commands listed above work as expected.
Znodes stay up as reliably as they had been...

## Steps to reproduce
 1) Load zcoin software on Ubuntu 16.04 1GB mem, 1 CPU, 40GB machine
 2) Configure a znode, sync the blockchain, start masternode.
 3) Find node in NEW_START_REQUIRED state, find that any of the above `cli` commands produce the same JSON parsing error.

Sorry, I know step 3 sucks as a repro step, but it's all I've got...
Additional info:
 - I've got other znodes that seem quite happy with 0.13.8.3, so I don't know that it's that version of the software, but the last 2 I've setup have both been acting this way.
I'll attach more details as this error repeats...

**Comment by reubenyap** [comment]
We think this is solved by #612 

If you compile a debug build and you may be able to see the race condition similar but let us know!

**Comment by reubenyap** [comment]
Thank you for reporting this! We were working on it already but always good to have further feedback.
