### ISSUE TITLE
Prevent double mint

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/zcoin#624]
We should prevent user to create mint when we found the same commitment is in chain state in both client and consensus level.
1) in client if we found the same commitment in network we should throw error
2) in consensus level we should consider the TX as a failed TX, and do not subtract balance.

**Comment by ultimaweapon** [comment]
@thebevrishot could you provides more information?

**Comment by ultimaweapon** [comment]
After discussion we don't need to do this.
