### ISSUE TITLE
Older clients should be banned upon version check.

### ISSUE THREAD

**Issue by azilber** [zcoinofficial/zcoin#633]
The latest client seems to communicate and exchange large chunks of network data with old (pre-forked) clients.  Their ban score is still 0, and the client keeps connections open to old wallets.

What should happen:  Upon detecting a pre-fork version, client should set a ban score and disconnect from the old wallet/znode.

![old-xzc](https://user-images.githubusercontent.com/691270/63344620-6a1e1800-c383-11e9-8c77-dec6536bcf27.png)

As you can see from the screenshot above, over 45mb of network traffic was wasted, and the ban score is still zero on client that is still keeping a connection open.

**Comment by azilber** [comment]
This could also be an issue if you're setting maxconnections in your zcoin.conf to a low number, as old clients will sit on connections instead of being banned.

**Comment by qashban4** [comment]
Could be 2 hour work or so

**Comment by qashban4** [comment]
@ultimaweapon see if we can conclude this week or beginning of next week, so we can close its only 2 hour effort.

**Comment by ultimaweapon** [comment]
Just notice that we changed our protocol number back to `90026` for Sigma client so this will get more complicated works.

**Comment by azilber** [comment]
Looks like this is already resolved with #742 ?

**Comment by ultimaweapon** [comment]
Right. I will close this now.
