### ISSUE TITLE
Fix transaction list for spend

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/zcoin#634]

**Comment by thebevrishot** [comment]
![transactionlistbug](https://user-images.githubusercontent.com/23252700/63425327-7a44fe80-c43a-11e9-8095-2b417aa5a62e.png)

**Comment by thebevrishot** [comment]
also investigate field address for spending.

**Comment by ultimaweapon** [comment]
This one no need to be release with Sigma so I will remove it from project and milestone.

**Comment by thebevrishot** [comment]
![Exodus_mintspend](https://user-images.githubusercontent.com/23252700/73261460-b442d980-41fe-11ea-9407-8ac238d10e02.png)
