### ISSUE TITLE
Change recording mint and serial operations in Sigma DB to be automic

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/zcoin#638]
For example we have two steps in create mint in db which are
1) record mint itself
2) record history

right not it's separated and have no rollback mechanism. I think we should use batch function of Level DB to make it be atomic.

- [x] Implementation [3]
- [x] Review [1]

**Comment by ultimaweapon** [comment]
@thebevrishot could you provides more information?

**Comment by thebevrishot** [comment]
added
