### ISSUE TITLE
Cant synced,Error: Node does not have mint zerocoin to verify, please wait until

### ISSUE THREAD

**Issue by saymissme** [zcoinofficial/zcoin#64]
```
2017-02-11 00:23:06 c2012495082d89d00ff7f4dea60443d42a4aec921d173594dde3b6f778febae3 from 46.101.31.112:8168 /Satoshi:0.8.7.2/ was not accepted into the memory pool
2017-02-11 00:23:09 received block dbb1f60bf48af90e1ab1db93d1b08ecd8818dfa25f9d7cae6c52d628ad83a448
2017-02-11 00:23:09 ERROR: CTransaction::CheckTransaction() : Error: Node does not have mint zerocoin to verify, please wait until
2017-02-11 00:23:09 ERROR: CheckBlock() : CheckTransaction failed
2017-02-11 00:23:09 ERROR: ProcessBlock() : CheckBlock FAILED
```

 ```
   "version" : 80704,
    "protocolversion" : 90020,
    "walletversion" : 60000,
    "balance" : 0.00000000,
    "blocks" : 20445,
    "timeoffset" : -1,
    "connections" : 8,
    "proxy" : "",
    "difficulty" : 0.02085286,
    "testnet" : false,
    "keypoololdest" : 1486394063,
    "keypoolsize" : 101,
    "paytxfee" : 0.00000000,
    "mininput" : 0.00001000,
    "errors" : ""
```

Cant synced
how to fix it?

@aizensou @djm34 @

**Comment by aizensou** [comment]
You probably has a bad zerocoin tx in your wallet. Does reindex help ?

**Comment by JazzMaster** [comment]
no, its the blockchain. its not sync. Two peices to this. 670/720 freeze--I cheated and used a blockchain(all but wallet and .conf) copy to sin box o get around, and a wallet write error thats going undiagnosed. I thought my thumb drive was going bad but its always this file. If this continues, its impossible to get paid and sync the wallet. I had to switch to ubu14 to mine with(sin is on the tower/rig) and the wallet needs to be able to be opened on all platforms. I cant speak for mac, my results lately of running non-intel hackitosh are sketchy. I can however try to use qemu on snow and yosemite.

**Comment by JazzMaster** [comment]
i copied the blocks from ubu16 box.

**Comment by dingjun1114** [comment]
copy wallet.dat from other platform,such as windows.then run app on osx with flag reindex,everything works well.

**Comment by dingjun1114** [comment]
@saymissme

**Comment by reubenyap** [comment]
This is now solved with the new core update.

https://github.com/zcoinofficial/zcoin/tree/core_upgrade.

Please reopen if still an issue.
