### ISSUE TITLE
Update Gitian descriptors to use latest Ubuntu LTS

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#642]
Right now we still use 14.04 which is already end of life. The problems with this is:

- We may not able to setup build environment due to the packages already removed.
- If there is some major bugs in the build tools we will not get those fixes.

The first issues is critical one because we will not be able to build a release. The second issue depend on how critical it is.

For me we should upgrade to 18.04, which is the latest LTS. Once Gitian descriptors was updated we need to test it in the developer machine first. When everything worked fine create a PR and once it merged consult @ultimaweapon for how to update Jenkins configurations.

**Comment by reubenyap** [comment]
Agree, I think even internally we don't even use 14.04 now.

**Comment by qashban4** [comment]
@riordant to start after releasing GUI 1.0

**Comment by a-bezrukov** [comment]
Done with core14
