### ISSUE TITLE
Mints not removed from the wallet when minting fail

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#660]
Example scenario:

- Wallet created mints and already stored.
- Call to function after mints created and it fail (e.g. `WalletTxBuilder`).

This will leave the created mint in the wallet.

- [x] Implementation [1]
- [x] Review [0.5]

**Comment by qashban4** [comment]
@thebevrishot assign reviewers if we need to review to be able to merge.

**Comment by qashban4** [comment]
@ultimaweapon to review on 2019-09-26 and merge to Exodus branch
