### ISSUE TITLE
Runaway exception "A fatal error occured.  Zcoin can no longer continue safely and will quit".

### ISSUE THREAD

**Issue by Brygarv** [zcoinofficial/zcoin#666]
Windows (10) / Running a node via VPS with 55GB SSD and 2048MB memory / OS Ubuntu 19.04 x64

I have deleted and reinstalled the wallet several times.  I have tried ./zcoin-qt.exe -reindex and thats when I get the error message.  When I click on the wallet.exe it shows the wallet is trying to load however, then it disappears.  The wallets block status in putty is up to date.   Even though the wallet startup display disappears after I receive the error message, I can see, 
"Zcoin Core (GUI node for Zcoin)" running in task manager.

**Comment by riordant** [comment]
Hi, could you give details on what you were doing in the wallet before the error occured?

**Comment by reubenyap** [comment]
Closing this issue as no response. Please reopen if still an issue and replicable.
