### ISSUE TITLE
Ban v0.13.7.x from network

### ISSUE THREAD

**Issue by justanwar** [zcoinofficial/zcoin#674]
With the majority of nodes now on v13.8.x I propose that nodes on v0.13.7.x to be banned or rejected. Currently v13.8.x can sometime still connect to the older version if they are around.

The following problems were observed when a node connects to peers on 13.7.x:

1. On wallet start, blockchain sync time increased because the peer is running v0.13.7.x and is stuck on 184213 so the wallet have to wait for more v0.13.8.x peers to connect before disregarding the v0.13.7.x peer (sometimes more than 5 minutes);

2. Peers running v0.13.7.2 can still be found running on the network which leads to increased/excessive bandwidth consumption on the node that connects to v0.13.7.2 peer. This was fixed in v0.13.7.4 but non-upgraded v0.13.7.2 will continue to exhibit this behaviour;

3. v0.13.7.x peers also might have been interfering with the Znode list.

**Comment by psolstice** [comment]
Will be done during core upgrade

**Comment by justanwar** [comment]
Will be implemented in #742
