### ISSUE TITLE
Add flag to run exodus regression test

### ISSUE THREAD

**Issue by thebevrishot** [zcoinofficial/zcoin#679]
same as `qa/pull-tester/rpc-tests.py -extended` we need more flag to tell we need to run exodus regression test. Also need to disable the test by default.

**Comment by ultimaweapon** [comment]
This one is not required for Sigma so I will remove it from project.

**Comment by qashban4** [comment]
We shall close this issue as its nor required as mentioned below:
"This one is not required for Sigma so I will remove it from project."
