### ISSUE TITLE
100% CPU Usage

### ISSUE THREAD

**Issue by wanghaoqd** [zcoinofficial/zcoin#68]
Hi,
I was planning to build up a mining pool. So I compiled zcoind from source on my VPS (Ubuntu 14.04 64bit).
The zcoind keep running at 100% CPU utilization while syncing. After 3 days it finally finished synchronization, but the CPU usage remains 100%.
I've checked the .conf file, and confirmed it was not mining.
Then I tried the windows Qt wallet on another VPS which has a Windows Server 2012 system. The situation was the same: slow synchronization and 1 CPU core always full-loaded.
On therse 2 servers I've tried 0.2.0, 0.2.1, 0.8.7.6, all has this problem.

But on another vm which has Windows 7 SP1 64bit OS, the CPU usage is fine, always below 5%.
What may be the problem? Any suggestions?

**Comment by wanghaoqd** [comment]
My pool is running now, found 1 block but the CPU usage is still 100%.

**Comment by wanghaoqd** [comment]
my pool has mined 70 blocks. but the wallet's cpu usage remains 100%
http://xzc.newpool.top/index.php?page=statistics&action=blocks
![default](https://cloud.githubusercontent.com/assets/4500569/23977674/70c30658-0a2a-11e7-8e1c-19fe3b1a52ca.png)

**Comment by wanghaoqd** [comment]
![default](https://cloud.githubusercontent.com/assets/4500569/23977856/b1aa56d4-0a2b-11e7-90e5-3c3341792acc.png)

**Comment by kEviN1H** [comment]
My network has a problem. Is there a manual or instruction to build POOL?

**Comment by reubenyap** [comment]
Could you test this with the new core?

https://github.com/zcoinofficial/zcoin/tree/core_upgrade.

**Comment by wanghaoqd** [comment]
OK. I'll try the new version and report back.

**Comment by wanghaoqd** [comment]
Upgrading to the new version 0.13.2.4 did fixed this issue. Thanks!

**Comment by DeadManWalkingTO** [comment]
In some cases (unfortunately many), the processors in Windows 10 show 100% usage.
From what I understand the problem grows according to the number of GPUs.
Windows 10 overloads processors that have few flames when GPUs are more than the threads.

I found some tweaks for windows 10 and achieve more than 50% less CPU usage.

New CPU Usage: 45% 

[Windows10MiningTweaksDmW](https://github.com/DeadManWalkingTO/Windows10MiningTweaksDmW)

Just let me know about your results.

Have a nice mining!
