### ISSUE TITLE
Store transaction ID for each mint

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#687]
This will allow to lookup which transaction is created it.

This is wallet level only.

- [x] Implementation [2]
- [x] Review [0.5]

**Comment by qashban4** [comment]
To be completed by 2019-09-27

**Comment by ultimaweapon** [comment]
After discussion in standup meeting this one is blocked by #627.

**Comment by qashban4** [comment]
@ultimaweapon to work on this on 2019-10-02 as there is dependency to #627
