### ISSUE TITLE
RPC error JSONRPC error: argument 1 must be hexadecimal string (not '0100000001d7f58d9fc5d239fc9ee4a849717322c0517fbb58e022c5e13a4f8041af53045b00000000001111111101c0aff629010000001976a9147e425376b2e07d764d642e6eb66ca3ff2933a2ef88ac100000000')

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#700]
## Actual behaviour
failing

## Desired behaviour
should not fail

## Steps to reproduce
1. Generate 200 blocks
2. Create a block-height-locked transaction which will be invalid after reorg 

```python
       timelock_tx = self.nodes[0].createrawtransaction([{"txid": coinbase_txids[0], "vout": 0}], {node0_address: 49.99})
       # Set the time lock
       timelock_tx = timelock_tx.replace("ffffffff", "11111111", 1)
       timelock_tx = timelock_tx[:-8] + hex(self.nodes[0].getblockcount() + 2)[2:] + "000000"
       timelock_tx = self.nodes[0].signrawtransaction(timelock_tx)["hex"]
```

E.g. if you are generate smaller size blocks - like 100 it will pass.

This is issue migrated from Trello reported by Mariia. Need to investigate to see if it still valid.

**Comment by levonpetrosyan93** [comment]
There is no issue here. Number of blocks causes sting size to be odd, but IsHex() function expects it to be even, that is why it gives an error. We can close this for now.
