### ISSUE TITLE
RPC mint command validation returns code with msg in some cases

### ISSUE THREAD

**Issue by ultimaweapon** [zcoinofficial/zcoin#701]
## Actual behaviour
```
['message'] =    (-8, 'Amount to mint is invalid.')
['code'] = -8
```

## Desired behaviour
```
['message'] = Amount to mint is invalid.
['code'] = -8
```

## Steps to reproduce
Call rpc comand `mint 0.1`.

This is issue migrated from Trello reported by Mariia. Need to investigate to see if it still valid.

**Comment by qashban4** [comment]
We wait until someone reports this issue or gets impacted.

**Comment by thebevrishot** [comment]
I got the response message below when try to mint with invalid amount. This should not be issue anymore.
```
{
    "error": {
        "code": -8,
        "message": "Amount to mint is invalid.\n"
    },
    "id": null,
    "result": null
}
```
