### ISSUE TITLE
Sigma spends to self show wrong date after reimporting from dump

### ISSUE THREAD

**Issue by reubenyap** [zcoinofficial/zcoin#718]
## Actual behaviour

Sigma spends to self show wrong date after reimporting from a dumpwallet and appear to be the same time as the latest incoming transaction.

This is in QT.

Number of confirmations are displayed correctly.

## Desired behaviour

Sigma spends to self should show correct date even after reimport.

## Steps to reproduce
This was tested on latest master build 740309e82 and also latest release 13.8.4 which both show the same issue.

However 13.8.4 7a38885 also incorrectly displays in Sigma mints, mints that have already been spent. listsigmamints shows all mints as unspent.

740309e82 displays it correctly.

*Step 1* Do a dumpwallet of a wallet with some existing spends to self.
*Step 2* Backup existing wallet.dat and rename to something else and delete wallet.dat to force client to create new empty wallet.dat
*Step 3* Restart client and let it sync
*Step 4* importwallet from the dump
*Step 5* Go to transaction list after completed import and rescan and you will see the spends to self have the wrong date.

**Comment by hexxcointakeover** [comment]
more on that, work more to solve the real issue

**Comment by riordant** [comment]
@reubenyap the time shown is the block time of the spend. `dumpwallet` only dumps keys, not wallet specific data like the time the transaction was created locally. When it syncs with the chain after `importwallet`, it assigns the block time to the transaction. This is the same for all transaction types. As a result I think this can be closed.

**Comment by reubenyap** [comment]
It's not the spend time it's reporting it wrongly. Those transaction dates are wrong but the block number is correct 




---- On Tue, 08 Oct 2019 19:23:34 +0800 notifications@github.com wrote ----



@reubenyap the time shown is the block time of the spend. dumpwallet only dumps keys, not wallet specific data like the time the transaction was created locally. When it syncs with the chain after importwallet, it assigns the block time to the transaction. This is the same for all transaction types. As a result I think this can be closed.

**Comment by reubenyap** [comment]
@riordant can this be closed?
