### ISSUE TITLE
sigma dump

### ISSUE THREAD

**Issue by hexxcointakeover** [zcoinofficial/zcoin#719]
## Actual behaviour
dumped wallet, with sigma mints on it
deleted old wallet, for sure, no backup
made new wallet, imported
imported wallet, got no sigma back, only normal keys imported back
lost all my sigma mints ( who will pay my loss?)

dump file had only normal keys,  sigma dump code missing from released wallets

**Comment by riordant** [comment]
Hi, our architecture is such that Sigma mints are derived from keys. These keys are dumped in `dumpwallet`. If you're mints confirmed, they are recoverable from `importwallet` (it will check the chain for your mints from the key data). If not, the keys used for them will be once again available in your imported wallet.

**Comment by reubenyap** [comment]
Confirmed that we couldn't replicate thie issue with 2-3 separate testers on different platforms/computers.

We have another cosmetic issue from import which is reflected in #718 

Closing this issue unless it's a problem on the Zcoin wallet.
