### ISSUE TITLE
add installation guide for fedora

### ISSUE THREAD

**Issue by rafid059** [zcoinofficial/zcoin#75]

**Comment by TheNT87** [comment]
CentOs also

**Comment by devwarrior777** [comment]
Hi, do you actually need to compile and build the code?

Runnable binaries are here:
- https://github.com/zcoinofficial/zcoin/releases/tag/v0.13.5.8

I am personally running this code on Fedora 23 in a XEN VM on Qubes as my main wallet.

May we close this issue?
