### ISSUE TITLE
Can't Send Exodus Sigma Spends Larger Than 0.01

### ISSUE THREAD

**Issue by catchingknives** [zcoinofficial/zcoin#759]
## Actual behaviour
Sending any amount higher than 0.01 results in 
```
Reference amount higher is than 0.01 XZC (code -3)
```

## Desired behaviour
Desired amount should be send.
Amounts should not be denominated in XZC as this is on Exodus layer.

## Steps to reproduce
- Create Exodus token
- Create Mint of any denomination (I tried 100)
- Try to Spend any amount higher than 0.01 (I tried 100, 50, and 1)

**Comment by thebevrishot** [comment]
Could you provide the arguments which you use to call spend?

**Comment by catchingknives** [comment]
Sure! Sorry.
```
exodus_sendspend <address> 3 0 100
```

Before that, I had created a several 100 mints with denomination ID 0

**Comment by catchingknives** [comment]
OK, seems like I misunderstood what reference amount means
