### ISSUE TITLE
dumpwallet command does not dump Zerocoin data

### ISSUE THREAD

**Issue by italicbold** [zcoinofficial/zcoin#760]
I have been waiting for https://github.com/zcoinofficial/zcoin/issues/541 to be in latest version of Zcoin client. However when I try dump my old wallet to get my zcoins into a new hd wallet the command crashes zcoin client.

## Client
Zcoin Core version v0.13.8.5-dc33dff (64-bit)

## Actual behaviour
Zcoin client crashes, empty file produced by dumpwallet. Nothing appended to debug.log

## Desired behaviour
Zcoin client does not crash and dumps zcoins with wallet

## Steps to reproduce
walletpassphrase "xxx" 120
dumpwallet "d:\wallet.txt" 
dumpwallet "d:\wallet.txt" xxx

**Comment by italicbold** [comment]
Folowing steps from https://zcoin.io/how-to-upgrade-your-legacy-zcoin-wallet-to-a-hd-wallet/

**Comment by italicbold** [comment]
Works fine in Zcoin v0.13.8.4-7a38885, but does not dump the zero coins.

**Comment by riordant** [comment]
Hi, from the steps you've shown, you're on Windows correct?

**Comment by italicbold** [comment]
Yes thats correct, Windows 10 version 1903.

**Comment by italicbold** [comment]
Just tested, same behavior on Ubuntu 16.04.6 LTS

**Comment by riordant** [comment]
Ive discovered the issue. Will push a fix soon

**Comment by riordant** [comment]
https://github.com/zcoinofficial/zcoin/pull/761 is the fix, we will do an interim release with it. Thanks

**Comment by italicbold** [comment]
thanks for the prompt turnaround!

**Comment by italicbold** [comment]
Hi, dumpwallet no longer crashes, however when I try and import tha dumped wallet the client displays an error and gets stuck on 2% pemenantly:

![Capture](https://user-images.githubusercontent.com/22705442/70298441-55fb0b00-17fa-11ea-9c92-b2b3c16a9407.JPG)

Console outputs **error: stoi (code -1)**

# Wallet dump created by Zcoin v0.13.8.9-beb6440
# * Created on 2019-12-05T17:12:13Z
# * Best block at time of backup was 220908 

Zcoin v0.13.8.9-beb6440 used for dump and import on windows 10.

Not sure if this issue is related to incorrect dump or import wallet, let me know if you want me to raise a new issue thanks.

**Comment by riordant** [comment]
Hi @italicbold , could you take a look at the dump file and check the `zerocoin=1` part. It should have the following layout (I have added a new line between each entry):
```
zerocoin=1 
79a0b9bbf0dc34cc26de5bd64e0b24bcc4e24561e75ff920639a5b5b2f0f72442cad2915c98ec89815be0d0222743adc5971c90605a4f30c913751067819765ae870bfa3c952679e20e29ef48b003205b07fcd6971384e4c6c5534ac6f81808d14a8dfefd2afed95e61c0daebf677cb4c8c053e9a48b363da0f1fd95a7cafc61 
1 
12d495036bf18f1a3dcee28d94d36d5725ae63562af22c3974196173cd23fec6 
ec9ad3d3be02cfb7defc75287ec2d6366d4326e0 
0 
-1 
-1 
63a914fc95602d0a49119f13b53fc1067894c53e3cb291f97b89b561982200bf 
0
```

Could you please count the number of entries here and see if it matches? it seems from your error report that it's trying to read one of these from the dump file but it's not there.

**Comment by riordant** [comment]
@italicbold When roughly were your Zerocoins created? I've discovered an issue in import with older Zerocoins

**Comment by italicbold** [comment]
Hi, all minted in January 2019.

**Comment by italicbold** [comment]
Dump file has 3700~ lines starting with zerocoin=1 

Each line is format: `zerocoin=1 string int 0 0 0 int int #` when using space as a delimeter.

This is more lines than I have coins or mints starting with zerocoin=1
