### ISSUE TITLE
Sigma "Available amount to mint" should exclude locked spends.

### ISSUE THREAD

**Issue by azilber** [zcoinofficial/zcoin#762]
## Actual behaviour
When XZC is locked for znode use, the Sigma screen does not take the locked spends into account.

## Desired behaviour
Should deduct the znode amount(s) from the available amount to Sigma mint.

## Steps to reproduce
*Step 1* Setup Znode
*Step 2* Enter Sigma mint

**Comment by catchingknives** [comment]
@azilber You mean under `Available amount to mint`?

**Comment by reubenyap** [comment]
Hi @levonpetrosyan93 can you look into this? I agree that this is misleading and should be an easy fix. Could you work on this after mnemonics?

**Comment by reubenyap** [comment]
Solved by #799
