### ISSUE TITLE
Unable to build x86_64-linux-gnu depends

### ISSUE THREAD

**Issue by akshaynexus** [zcoinofficial/zcoin#790]
## Actual behaviour
fcmatch.c:284:63: error: 'PRI_CHAR_WIDTH_STRONG' undeclared here (not in a function); did you mean 'PRI_WIDTH_STRONG'?
 #define FC_OBJECT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
                                                               ^~~~
fcobjs.h:54:1: note: in expansion of macro 'FC_OBJECT'
 FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)
 ^~~~~~~~~
fcmatch.c:284:84: error: 'PRI_CHAR_WIDTH_WEAK' undeclared here (not in a function); did you mean 'PRI_WIDTH_WEAK'?
 #define FC_OBJECT(NAME, Type, Cmp) { FC_##NAME##_OBJECT, Cmp, PRI_##NAME##_STRONG, PRI_##NAME##_WEAK },
                                                                                    ^~~~
fcobjs.h:54:1: note: in expansion of macro 'FC_OBJECT'
 FC_OBJECT (CHAR_WIDTH,  FcTypeInteger, NULL)
 ^~~~~~~~~
make[4]: *** [Makefile:613: fcmatch.lo] Error 
## Related issue
https://github.com/servo/libfontconfig/issues/31
## Desired behaviour
Depends compile without issues and give built depends
## Steps to reproduce
Clone ZCoin repo
cd to depends
make HOST=x86_64-linux-gnu -j32
Wait until fontconfig  is getting compiled.
Get the error.

**Comment by akshaynexus** [comment]
Fixed with #792

**Comment by a-bezrukov** [comment]
I will follow up when ready with bionic

**Comment by a-bezrukov** [comment]
@akshaynexus It is very hard to merge this to master as this would be an unsupported workflow. This dir is used for gitian deterministic build. Gitian builds macOS binaries on a Linux container, but not wise versa.
So, I am picking some of your changes, and I am making it as similar to the upstream as possible to make future merges simpler.
