### ISSUE TITLE
Wallet stuck on block 223405, it banned a bunch of peers

### ISSUE THREAD

**Issue by chileminer** [zcoinofficial/zcoin#793]
## Actual behaviour
Wallet seems to be banning the synced nodes.
If you look in the upper left corner of the first image, I overlapped the main wallet page to show that the wallet thinks it is synced, since it banned all of the peers with a higher block height.   Every peer that it didn't ban has a lower block height.

## Desired behaviour
Not ban good nodes and sync.

## Steps to reproduce
I don't know how to reproduce. 
![image](https://user-images.githubusercontent.com/49484468/70851130-744ab180-1e5f-11ea-830b-01298ce64e3d.png)
![image](https://user-images.githubusercontent.com/49484468/70851148-96dcca80-1e5f-11ea-99d1-b1e88fc134b6.png)

**Comment by chileminer** [comment]
I tried "reconsiderblock  9cdc7a330b4bef06416235554085fb45001b298d41bcab82d17990d6b3bdb39f" with no success.

I'll leave the wallet like this for a while in case someone wants me to try something to gather more information on the problem.

**Comment by ZhiweiWang** [comment]
try "zcoin-cli clearbanned" could be help

**Comment by HysMagus** [comment]
@chileminer Could you try running your qt with debug=1 and seeing what the debug.log output is? It might shed some light of the behavior causing the banning

**Comment by reubenyap** [comment]
Closing this issue but feel free to open if it's still a problem!
