### ISSUE TITLE
https://bootstrap.zcoin.io/ is down again

### ISSUE THREAD

**Issue by lcgogo** [zcoinofficial/zcoin#805]
## Actual behaviour
https://bootstrap.zcoin.io/ is down now

## Steps to reproduce
- ReplaceMe: *Step 1*
- ReplaceMe: *Step 2*

**Comment by reubenyap** [comment]
We keep on being DDoSed so just use these two:
http://zcoinbootstrap.moranilabs.org/
https://files.privex.io/blockchains/zcoin/snapshot.tar.lz4

**Comment by lcgogo** [comment]
Thanks.

**Comment by 2ge** [comment]
thanks
