### ISSUE TITLE
`dandelion=0` Does Not in Fact Seem to Disable Dandelion

### ISSUE THREAD

**Issue by catchingknives** [zcoinofficial/zcoin#820]
## Actual behaviour
After putting `dandelion=0` in zcoin.conf or appending it to the `zcoind -daemon` command line, Dandelion log messages are still being produced

## Desired behaviour
Dandelion should be disabled and not produce any more log messages

## Steps to reproduce
1. Deactivate Dandelion
2. Still find new Dandelion log messages being written to debug.log

**Comment by a-bezrukov** [comment]
`dandelion=0` makes a node passing txes directly to mempools, bypassing the Dandelion stem pool broadcasting mechanism. At the same time, the node may take part in the Dandelion stem pools, providing the Dandelion functionality for the nodes with enabled Dandelion. That is where the Dandelion log messages come from.

**Comment by catchingknives** [comment]
Makes sense. Thanks for the explanation!
