### ISSUE TITLE
cross-compile on lxss fails on configure tor

### ISSUE THREAD

**Issue by Rav3nPL** [zcoinofficial/zcoin#821]
OS: Win10 x64
lxss: Ubuntu 18.04

Building dependencies w/o problem.
When try to
```
./configure --prefix=`pwd`/depends/x86_64-w64-mingw32 
```
it ends at 
```
=== configuring in src/tor
(...)
checking whether free(NULL) works... yes
checking for libevent directory... (system)
checking whether we need extra options to link libevent... configure: error: Found linkable libevent in (system), but it does not seem to run, even with -R. Maybe specify another using --with-libevent-dir}
```

Just before it stops windows is nagging about missing libwinpthread-1.dll 3 times.

**Comment by Rav3nPL** [comment]
Yes.

**Comment by ultimaweapon** [comment]
I guess it picks a wrong version of `libevent` from the one that installed in the system instead of the one that was built from `depends`. Could you verify this?

**Comment by ultimaweapon** [comment]
I will close this issue for now if you still having this issue please put a new comment.
