### ISSUE TITLE
Cant open wallet.dat

### ISSUE THREAD

**Issue by gkucmierz** [zcoinofficial/zcoin#83]
zcoin wallet is still broken on macos El Capitan!

<img width="498" alt="zrzut ekranu 2017-03-26 o 22 07 35" src="https://cloud.githubusercontent.com/assets/739084/24334768/cb3d168e-1270-11e7-98be-dcb7d306e5b7.png">

It also cant work with my wallet.dat created in early zcoin version on amazon ec2.
How can I recover that wallet?

**Comment by aizensou** [comment]
I look at your github and look like you're a coder as well. I don't know the reason why are you trying to spam the same problem over and over on github. It would be much nicer if you join slack and your problem could be solved much faster.
Anyway, if you have error -30974 or -30973, looks like you have a corrupted wallet.dat. It's almost the same with all bitcoin-based coins. A few users have reported the same problem and the solution is to try other backups of the wallets.
Or if you have the private keys, you could create new wallets and import them.
Hope that you are satisfied with this.

**Comment by gkucmierz** [comment]
There is no one on slack.
This wallet is one of top ten rich list. Please dont tell me it is corrupted as it was created with software compiled from this github repo.

**Comment by gkucmierz** [comment]
```
-----BEGIN BITCOIN SIGNED MESSAGE-----
I will pay 0,5 BTC for help with receiving this coins.
wallet.dat, privkeys or whatever
-----BEGIN SIGNATURE-----
13Ko3advBPQZnozVBM4h8LSn89GGmJ8t5E
HDbKfpckVDn6yg+Cop2+jyfr0Me4ecsJOvY/Hb2RXjWxQBMVLtZIsaGl0grQe9DnQLFDj1Mr0MswMMj/zUf4m4o=
-----END BITCOIN SIGNED MESSAGE-----
```
