### ISSUE TITLE
Build is failing in Ubuntu, no idea where to find the "protoc", what it is or what autotools or linker component is looking for it

### ISSUE THREAD

**Issue by Sviluppo718** [zcoinofficial/zcoin#831]
Errors in the make step are as follows:

```make[3]: Leaving directory '[snip]/zcoin/src/secp256k1'
  CXX      libbitcoin_server_a-init.o
  AR       libsigma.a
/usr/bin/ar: `u' modifier ignored since `D' is the default (see `U')
  CXX      qt/qt_zcoin_qt-bitcoin.o
In file included from qt/paymentrequestplus.h:8:0,
                 from qt/paymentserver.h:35,
                 from qt/bitcoin.cpp:27:
qt/paymentrequest.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
qt/paymentrequest.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
qt/paymentrequest.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
make[3]: Entering directory '[snip]/zcoin/src/tor'
make  all-am
make[4]: Entering directory '[snip]/zcoin/src/tor'
make[4]: Leaving directory '[snip]/zcoin/src/tor'
make[3]: Leaving directory [snip]/zcoin/src/tor'
  CXX      qt/qt_libzcoinqt_a-bitcoingui.o
In file included from qt/paymentrequestplus.h:8:0,
                 from qt/walletmodel.h:8,
                 from qt/bitcoingui.cpp:26:
qt/paymentrequest.pb.h:17:2: error: #error This file was generated by an older version of protoc which is
 #error This file was generated by an older version of protoc which is
  ^~~~~
qt/paymentrequest.pb.h:18:2: error: #error incompatible with your Protocol Buffer headers. Please
 #error incompatible with your Protocol Buffer headers.  Please
  ^~~~~
qt/paymentrequest.pb.h:19:2: error: #error regenerate this file with a newer version of protoc.
 #error regenerate this file with a newer version of protoc.
  ^~~~~
Makefile:10869: recipe for target 'qt/qt_zcoin_qt-bitcoin.o' failed
make[2]: *** [qt/qt_zcoin_qt-bitcoin.o] Error 1
make[2]: *** Waiting for unfinished jobs....
Makefile:8923: recipe for target 'qt/qt_libzcoinqt_a-bitcoingui.o' failed
make[2]: *** [qt/qt_libzcoinqt_a-bitcoingui.o] Error 1
```

my ```autogen.sh``` line worked with no evident problems
the configure line was built in reference to a pre-built Berkeley 4.8 instance located with absolute pathnames

```$ ./configure LDFLAGS="-L${BDB_LIB}/" CPPFLAGS="-I${BDB_INCLUDE}/" --with-gui=qt5 --disable-upnp-default --without-miniupnpc```
That line also ran with no evident errors or relevant warnings.  The errors listed above were after running make.

Is my system too up-to-date for this and I need to downgrade something? (not a desired solution IMO).  In keeping with this principle, I don't want to downgrade from the stock BerkeleyDB under Debian/Ubuntu ( https://wiki.debian.org/BerkeleyDB ) to the "classic" Bitcoin one BTW (hence referring to the pre-built Berkeley 4.8 that I have in the wings for the altcoin wallets that require it... sure wish more went with LMDB like Monero :P ).

**Comment by a-bezrukov** [comment]
Hi There, 

It just looks your `protoc` compiler is too up-too-date. Two options are here: downgrade the compiler or regenerate the ProtoBuf output: `rm ./src/qt/paymentrequest.pb.*; make ./src/qt/paymentrequest.pb.cc` and make it again.

RSVP

**Comment by Sviluppo718** [comment]
That seemed to do the trick very deftly for that but I entered whack-a-mole territory here: now make is looking for something from boost:

  OBJCXXLD qt/zcoin-qt
libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `StopHTTPServer()':
/usr/local/include/boost/thread/detail/thread.hpp:753: undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
collect2: error: ld returned 1 exit status
Makefile:4888: recipe for target 'zcoind' failed
make[2]: *** [zcoind] Error 1
make[2]: *** Waiting for unfinished jobs....
libbitcoin_server.a(libbitcoin_server_a-httpserver.o): In function `StopHTTPServer()':
/usr/local/include/boost/thread/detail/thread.hpp:753: undefined reference to `boost::thread::do_try_join_until_noexcept(boost::detail::mono_platform_timepoint const&, bool&)'
collect2: error: ld returned 1 exit status
Makefile:4556: recipe for target 'qt/zcoin-qt' failed
make[2]: *** [qt/zcoin-qt] Error 1
make[2]: Leaving directory '[snip]/zcoin/src'
Makefile:12730: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '[snip]/zcoin/src'
Makefile:691: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1

My boost version is 1.65.1.0ubuntu1
$ whereis boost # outputs /usr/include/boost
$ dpkg -s libboost-dev # outputs more extensive info

**Comment by a-bezrukov** [comment]
I am guessing you are using Ubuntu 18.04 (please let me know if you are not). With Ubuntu 18.04 it builds OK following these build instructions https://github.com/zcoinofficial/zcoin#linux-build-instructions-and-notes

**Comment by Sviluppo718** [comment]
Yep, Ubuntu 18.04.  I got it to build, it's synced, and running now (although I did have a lot of boost instances built in /usr/local/ ).

Even after purging many of those (perhaps unnecessarily, but also a few other things [i386 libraries/repositories and an openssl conflict that may have impacted on other builds]) the following configure line seemed to work only when it was told where to find boost.  The line was:
```./configure LDFLAGS="-L${BDB_LIB}" CPPFLAGS="-I${BDB_INCLUDE}" --without-miniupnpc --with-gui=qt5 --with-boost-libdir=/usr/local/lib```

I'm still using an instance of a locally-built Berkeley db-4.8.30,  That's because I'm trying not to cause conflicts with the configuration that is supported by the Ubuntu developers and Canonical.  For example, **simulating and not installing** db-4.8 and its C++ libraries:
``` $ sudo apt-get -s install libdb4.8-dev libdb4.8++-dev ```

tells me that:
```
Package libdb4.8++-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package libdb4.8-dev is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libdb4.8-dev' has no installation candidate
E: Package 'libdb4.8++-dev' has no installation candidate
```

Whereas this status information:
```$ dpkg -s libdb5.3++-dev```
shows that the 5.3 version is installed and 'ok' and that it conflicts with libdb4.8++-dev (actually versions 4.6 to 5.2).

**If anyone wants to build Berkeley 4.8.30 locally (and not potentially affect other libraries or otherwise hamstring your system)...** I've encountered these directions elsewhere but want to pass the favor along with some further suggestions:

Oracle still hosts it -- though their production verson is now 18.1 -- here: https://www.oracle.com/database/technologies/related/berkeleydb-release-history.html .

I used the "Berkeley DB 4.8.30.tar.gz, with AES encryption" (not the NC version without encryption)

Make a directory for it and move that "tarball" file there.

You might want to compare its SHA-256 checksum to ensure the copy isn't corrupt.  I found the checksum here: https://www.freshports.org/databases/db48/ . (Courtesy of the folks at FreeBSD)

```$  echo 'e0491a07cdb21fb9aa82773bbbedaeb7639cbd0e7f96147ab46141e0045db72a db-4.8.30.tar.gz' | sha256sum -c```
Outputs: db-4.8.30.tar.gz: OK
It can also be checked by ```$ sha256sum db-4.8.30.tar.gz```
 
In the directory where you want to build it, create a BASH variable to reference your current directory:

```
$ BDB_PREFIX=$(pwd)    # Note there can be no spaces for shell variables and it's case-sensitive
$ echo $BDB_PREFIX       # Allows you to check that it uses an absolute (not relative) address
```

Now you have a reference to your database's root directory and know the tarball is valid, so:
```
gzip -d db-4.8.30.tar.gz          # decompress it
tar xf db-4.8.30.tar                 # extract the archive
rm db-4.8.30.tar                     # the archive is no longer needed, removing
cd db-4.8.30/build_unix         # must be compiled in BerkeleyDB's unix sandbox (using relative paths)
```

In the build_unix directory:
```$ ../dist/configure --enable-cxx --disable-shared --with-pic --prefix=$BDB_PREFIX --exec-prefix=$BDB_PREFIX```

These options for the configure script:
- enable the C++ API
-  build a static (non-shared/dynamic) library that can be modularly incorporated into the executable rather than looking for a .so file at run-time
- build with position-independent code (better security usually, also more modular) and
- --prefix and --exec-prefix point where to install "architecture-independent" and "architecture-dependent" files, respectively.

I'd suggest checking that the makefile installs stuff where you think it will.  You can open it with an editor or use gnu's head utility to look at the first 18 lines of the file to confirm this:

```$ head -n 18 Makefile```

In particular, check that prefix and exec-prefix aren't set to install in their default location
( /usr/local/BerkeleyDB.4.8 ) which potentially can cause conflicts on your system.

Also, I've found that it won't make/build correctly if your BDB_PREFIX was set to the db-4.8.30 directory (it's probably overwriting files/stepping on its own toes... use the directory that you initially started working in -- its parent directory -- instead).

If everything looks good:
$ make
$ make install

(Notice that I didn't type sudo before either of these.  You'll cause less havoc if you can keep in the userspace and don't go to super-user when building stuff.)

Finally, some cleanup...  Wherever your BDB_PREFIX directory is, the make install command created bin, docs, include, and lib directories.  The docs is actually a duplicate of db-4.8.30/docs so:
```
cd $BDB_PREFIX && ls
rm -rf docs/* && rmdir docs
```
You can also move the bin, include, and lib into db-4.8.30 (all in one convenient folder) without clobbering anything:
```mv bin include lib db-4.8.30```

**For the configure line used to make zcoin** (that is using the Berkeley DB instance you just built), I set a couple other BASH variables.  _Assuming you moved lib and include into db-4.8.30 and you're working in the parent folder_, you can set and check those variables as:

```
$ BDB_LIB=$(pwd)/db-4.8.30/lib && echo $BDB_LIB
$ BDB_INCLUDE=$(pwd)/db-4.8.30/include && echo $BDB_INCLUDE
```
Also, if you made Berkeley DB stuff somewhere you didn't want to, you want to redo some steps, or uninstall the thing: go to the build_unix directory and type:  ```make uninstall```, or ```make clean``` or ```make realclean``` (as appropriate).

Incidentally, I stumbled across information regarding the original errors (protocol buffers being part of the boost conlict) and the 'protoc' in the original question -- something that had roots in some Google framework I guess:

```
$ dpkg -s protobuf-compiler
$ dpkg -s libprotobuf-dev
```
