### ISSUE TITLE
Make not working

### ISSUE THREAD

**Issue by gkucmierz** [zcoinofficial/zcoin#84]
branhc v0.8.7.7
also the same on master

<img width="899" alt="zrzut ekranu 2017-03-27 o 00 42 23" src="https://cloud.githubusercontent.com/assets/739084/24335914/5ad4ecf8-1286-11e7-9803-776af2027961.png">

Ubuntu 16.04
amazon ec2 medium, 2 cores, 4gb

**Comment by TimurKiyivinski** [comment]
You are missing `g++`

**Comment by aizensou** [comment]
First, you probably join the wrong slack. Our slack is zcoinofficial.slack.com, and it's pretty active.
Second, you have to follow the instruction here https://github.com/zcoinofficial/zcoin/blob/master/doc/build-unix.md
If you don't even know how to fix these above errors, opening 100+ issues on github would be pointless. Joining slack for more interactive help would be much faster.
Third, we don't need your 0.5 BTC. Please join slack, maybe other users might be interested in helping you with that.
