### ISSUE TITLE
User Reported Bug: Exception in coins.cpp

### ISSUE THREAD

**Issue by HysMagus** [zcoinofficial/zcoin#854]
### Describe the issue
A community member experienced the following error upon updating from 13.8 to 14.0 on Windows Desktop
`Assertion failed. coins.cpp line 237`

### Can you reliably reproduce the issue?
The user is able to reproduce the issue
#### If so, please list the steps to reproduce below:
1. User attempts to open the 14.0 wallet after updating from 13.8

### Expected behaviour
Wallet should open
### Actual behaviour
`Assertion failed. coins,cpp,line 237`
### What version of bitcoin-core are you using?
0.14.0
### Machine specs:
- OS: Windows 10 Desktop
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

**Comment by justanwar** [comment]
User most likely running 0.13 binary instead of 0.14. Investigating.
