### ISSUE TITLE
The URL of the binary assets for the v0.14.0.0 is inconsistent

### ISSUE THREAD

**Issue by RonaldLaeremans** [zcoinofficial/zcoin#861]
For instance using the linux tar
Link for v0.14.0.0 is
https://github.com/zcoinofficial/zcoin/releases/download/v0.14.0.0/zcoin-0.14.0-linux64.tar.gz

Link for v0.13.8.10 is
https://github.com/zcoinofficial/zcoin/releases/download/v0.13.8.10/zcoin-0.13.8.10-linux64.tar.gz

So going with the pattern from earlier releases, I expect the link for v0.14.0.0 to be
https://github.com/zcoinofficial/zcoin/releases/download/v0.14.0.0/zcoin-0.14.0**.0**-linux64.tar.gz

This is breaking my automation.

**Comment by a-bezrukov** [comment]
It's several build systems acting. I'll fix it for the next releases.
