### ISSUE TITLE
Deterministic Znode 64: version (code -26)

### ISSUE THREAD

**Issue by Germaniy-Grom** [zcoinofficial/zcoin#864]
upon registration, Znode throws an error 64: version (code -26), what am I doing wrong? maybe there is a video instruction?

**Comment by NorseGaud** [comment]
Is `error 64: version (code -26)` it? Or is there more of an error?

**Comment by clu8** [comment]
I am getting this as well while following the instructions at https://github.com/zcoinofficial/zcoin/wiki/Migrating-your-Legacy-Znodes-to-the-new-Deterministic-Znodes-system. 

The message is `64: version (code -26)` only.

**Comment by NorseGaud** [comment]
Are you guys running the register command from a v0.14.0.1 client's console? Can you provide a bit more details about exactly what your environment and actions are like (redacting secrets)?

**Comment by clu8** [comment]
Upgrading from v0.14.0.0 to v0.14.0.1 fixed the issue. Thanks for the reminder.

**Comment by Germaniy-Grom** [comment]
v0.14.0.1 fixed the issue
