### ISSUE TITLE
Zcoin v0.14.0.1 does not start (make sure server is running and you are connecting to the correct RPC port)

### ISSUE THREAD

**Issue by Germaniy-Grom** [zcoinofficial/zcoin#865]
when trying to run ~ / zcoin-0.14.0 / bin $ ./zcoind -daemon
gives an error message
error: couldn't connect to server: unknown (code -1)
(make sure server is running and you are connecting to the correct RPC port)

**Comment by NorseGaud** [comment]
What does your config look like?

**Comment by justanwar** [comment]
Is `znodeprivkey` line still in conf?

**Comment by Germaniy-Grom** [comment]
> What does your config look like?

does not start with this config
#----
rpcuser=ANYUSERNAME
rpcpassword=ANYPASSWORD
rpcallowip=127.0.0.1
#----
listen=1
server=1
daemon=1
logtimestamps=1
txindex=1
#----
znode=1
externalip=18*.18*.1*.19*:8168
znodeprivkey=0ba80d206b22c93996d02c5****6d021f935fc675cc4fe9a03d44be5b75********
znodeblsprivkey=0ba80d206b22c93996d02****f6d021f935fc675cc4fe9a03d44be5b75********

**Comment by Germaniy-Grom** [comment]
if you remove znode = 1 in the config, it starts to run, how correct is it?

**Comment by justanwar** [comment]
When `znode=1` is set, znodeprivkey and znodeblsprivkey must be present and are using the correct key format. There should be log entries that might or might not say something is wrong with znodeprivkey.

znodeblsprivkey is generated with `bls generate`, while znodeprivkey is generated with `znode genkey`. They must not be of the same value.

The requirement for znodeprivkey if `znode=1` is present will be dropped in future versions, but as of now it must be there.

**Comment by justanwar** [comment]
Closing this for now, feel free to reopen if issue persists.
