### ISSUE TITLE
Logs vs privacy

### ISSUE THREAD

**Issue by skironDotNet** [zcoinofficial/zcoin#874]
Why are logs exposing owner addresses and pub key? It's possible to obtain a list of masternode owners just by running a node.
While it can't be maybe directly linked to a person it's still bad idea to expose all of that in logs, in my opionion
![image](https://user-images.githubusercontent.com/2981715/86674799-a9b31a00-bfbe-11ea-96d9-ed824d8bc52c.png)

**Comment by skironDotNet** [comment]
To elaborate more. lets use this node as an example

> MN 14f0fa47d55dc7176bab852feb0ae94532441a59375d368a1ab72c320f196a4b added at height 278536: CProRegTx(nVersion=1, collateralOutpoint=COutPoint(f38e76836947232dcf1fad87c3e741c075370cc7fc16ca96a47cc533ebac1528, 0), addr=154.118.14.4:8168, nOperatorReward=0.000000, ownerAddress=aLJHNVoED1eaoKKk9hLX2YhxhMpX4k72f1, pubKeyOperator=00746853fe0cf181fac190623f5c85f0960e673dfea0c32ae96bcb2d869978a54932a2a33ba6685489a6bc8b14011449, votingAddress=aLJHNVoED1eaoKKk9hLX2YhxhMpX4k72f1, scriptPayout=a6yCkKHBCXV2ZQUbPyPSpmbFFNvqCZJsSz)

Let say I'm an exchange knowing person X, that person sends 1000 XZC and staking to new owner address, supposed to be private? The person X spends funds from scriptPayout=a6yCkKHBCXV2ZQUbPyPSpmbFFNvqCZJsSz thinking the funds are private as they came from "nowhere" and there is no link between collateral and payout.

Now I'm an agent trying to figure out source of funds, so I take **ollateralOutpoint=COutPoint(f38e76836947232dcf1fad87c3e741c075370cc7fc16ca96a47cc533ebac1528, 0)** and check in public blockchain, now I have collateral address, and I know it links to payout address and I know person X made a payment.

Does it make sense?

**Comment by skironDotNet** [comment]
I guess hiding it from logs wouldn't do much, as if I were forensic agent, I would compile zcoin with my own custom code to dump back those logs for me. 

You could warn general public that it's deceiving that different payout address than znode collateral address could give you any privacy as I initially have thought.

**Comment by skironDotNet** [comment]
Haha, I just realized all this info is in ZNodes Tab. I guess you can close after reading my concerns. Thanks!

**Comment by reubenyap** [comment]
Znode collaterals are public and are designed in that way. Note that you can Sigma spend to make those collaterals come from no known source but you still need to tie a permanent IP address to the node and even in any other blockchain (even private ones), the existence of nodes are not hidden. You can always remint any payouts to Sigma.
