### ISSUE TITLE
mtp branch, stack corruption

### ISSUE THREAD

**Issue by tupieurods** [zcoinofficial/zcoin#88]
https://github.com/zcoinofficial/zcoin/blob/mtp/src/main.cpp#L6990
You allocate 64 bytes. And use this buffer in sprintf later. But sprintf automatically adds terminating null character.
http://www.cplusplus.com/reference/cstdio/sprintf/
And by real, it is pretty strange way to check number of trailing zeros in general. I hope it will be changed to a normal check before release.

**Comment by bu5hm4nn** [comment]
One should always prefer `snprintf` over `sprintf` anyways. That would protect the stack too.

**Comment by reubenyap** [comment]
Please look at refactor-mtp. There are some fixes to the stack but we are optimizing this further. 
https://github.com/zcoinofficial/zcoin/tree/refactor-mtp
