### ISSUE TITLE
Apologies - I supposedly have zcoin in a wallet at this address.  In fact I was able to login here.  But obviously this is not the page I belong on.  Can someone please tell me how to access my wallet?  I also have a note with my info that says you apparently only have phone wallets (this was in 2017 probably), but then why do I have this address for my zcoin?  Thank you for helping, and again, apologies for asking here.

### ISSUE THREAD

**Issue by bspaugh** [zcoinofficial/zcoin#908]
This issue tracker is only for technical issues related to bitcoin-core.

General bitcoin questions and/or support requests and are best directed to the [Bitcoin StackExchange](https://bitcoin.stackexchange.com).

For reporting security issues, please read instructions at [https://bitcoincore.org/en/contact/](https://bitcoincore.org/en/contact/).

#### If so, please list the steps to reproduce below:
1.
2.
3.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

### Screenshots.
If the issue is related to the GUI, screenshots can be added to this issue via drag & drop.

### What version of bitcoin-core are you using?
List the version number/commit ID, and if it is an official binary, self compiled or a distribution package such as PPA.

### Machine specs:
- OS:
- CPU:
- RAM:
- Disk size:
- Disk Type (HD/SDD):

### Any extra information that might be useful in the debugging process.
This is normally the contents of a `debug.log` or `config.log` file. Raw text or a link to a pastebin type site are preferred.

**Comment by justanwar** [comment]
What address? Which wallet is this? More information is required.

**Comment by justanwar** [comment]
Closing this. Feel free to reopen with new information.
