### ISSUE TITLE
Compile on Alpine 3.12 fails - includes fix

### ISSUE THREAD

**Issue by jTd7bPLFb** [zcoinofficial/zcoin#910]
To compile zcoind and zcoin-cli on Alpine 3.12 successfully, these are the small changes that need to be done.

Pre-requisites:
apk update
apk add build-base gcc abuild binutils autoconf automake \
         libtool pkgconf python3 py3-virtualenv db-c++ db-dev \
         gmp gmp-dev libevent libevent-dev git cmake boost-dev \
         openssl openssl-dev boost boost-dev zeromq-dev zlib-dev

Quickfix:
# patching src/httpserver.cpp for Alpine
#
echo '
diff file:
--- src/httpserver.cpp.ori
+++ src/httpserver.cpp
@@ -13,6 +13,8 @@
 #include "sync.h"
 #include "guiinterface.h"

+#include <deque>
+
 #include <stdio.h>
 #include <stdlib.h>
 #include <string.h>
 ' > patch01.diff
patch -p1 src/httpserver.cpp < patch01.diff

# patching src/Makefile.am for sigma zcoin unsupport
echo '
--- src/Makefile.am.ori
+++ src/Makefile.am
@@ -658,8 +658,8 @@
   crypto/MerkleTreeProof/merkle-tree.cpp \
   $(BITCOIN_CORE_H)

-libsigma_a_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES) -Werror
-libsigma_a_CXXFLAGS = $(AM_CXXFLAGS) $(PIE_FLAGS) -Werror
+libsigma_a_CPPFLAGS = $(AM_CPPFLAGS) $(BITCOIN_INCLUDES)
+libsigma_a_CXXFLAGS = $(AM_CXXFLAGS) $(PIE_FLAGS)
 libsigma_a_SOURCES = \
   sigma/r1_proof.h \
   sigma/r1_proof_generator.h \
' > patch02.diff
patch -p1 src/Makefile.am < patch02.diff

After this:
# compile
chmod -R u+x *
./autogen.sh
./configure LDFLAGS="-static-libstdc++" --enable-cxx --enable-static \
--disable-shared --disable-debug --disable-tests --disable-bench \
--with-pic --with-incompatible-bdb
make -j3
cd src
strip zcoind zcoin-cli zcoin-tx

**Comment by a-bezrukov** [comment]
Will be fixed with https://github.com/zcoinofficial/zcoin/pull/924
