### ISSUE TITLE
General data

### ISSUE THREAD

**Issue by davidhedlund** [zcoinofficial/zcoin#93]
I need to finish https://en.bitcoin.it/wiki/Comparison_of_cryptocurrencies

* How many units are "hard-wired" in to the protocol?
* Is the rest of the information correct or should I change anything?
* Do you want to add something to the comment column?

**Comment by nopslide** [comment]
@davidhedlund Anoncoin doesn't finish the zerocoin implementation as far as I know. Zcoin is the first and only cryptocurrency implemented zerocoin protocol for now. 

And for Proof-of-work, we are the first that implements Merkle Tree Proof of Work or MTP, which intend to solving issues in Equihash. MTP is created by the same author of Equihash.

**Comment by davidhedlund** [comment]
@nopslide Updated.

What is the mining fee?

**Comment by reubenyap** [comment]
Do you mean the block reward?

It follows the exact same schedule as Bitcoin except that for the first four years, 20% of the block reward (10 XZC per block) goes to the Founding wallets which include our funding for the team and the initial investors. After the four years, all the rewards go to the miners at least until we implement Znodes which will have a certain percentage given to Znode holders.
